export const contriesToFetch = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];
export const animalsLatinNames = [
    "Canis lupus familiaris",
    "Felis catus",
    "Equus ferus caballus",
    "Panthera leo",
    "Panthera tigris",
    "Ursus arctos",
    "Giraffa camelopardalis",
    "Elephas maximus",
    "Serpentes",
    "Crocodylidae",
    "Delphinus delphis",
    "Aptenodytes forsteri",
    "Macropus",
    "Phascolarctos cinereus",
    "Simia",
    "Vulpes vulpes",
    "Canis lupus",
    "Aves",
    "Pisces",
    "Selachimorpha",
    "Gorilla gorilla",
    "Hippopotamus amphibius",
    "Equus zebra",
    "Rhinoceros unicornis",
    "Struthio camelus",
    "Aquila chrysaetos",
    "Gallus gallus",
    "Anas platyrhynchos",
    "Pavo cristatus",
    "Bubo bubo",
    "Psittaciformes",
    "Erinaceus europaeus",
    "Panthera pardus",
    "Acinonyx jubatus",
    "Gazella",
    "Bubalus bubalis",
    "Camelus dromedarius",
    "Canis aureus",
    "Naja",
    "Formicidae",
    "Rana",
    "Iguana",
    "Phascolarctos cinereus",
    "Lutra",
    "Ovis aries",
    "Orcinus orca",
    "Panthera pardus",
    "Rattus",
    "Talpa",
    "Bos taurus",
    "Bos grunniens",
    "Balaenoptera",
    "Astacidea",
    "Mustela putorius furo",
    "Hylobates",
    "Cricetinae",
    "Panthera onca",
    "Oryctolagus cuniculus",
    "Marmota",
    "Monodon monoceros",
    "Otariidae",
    "Ailuropoda melanoleuca",
    "Setonix brachyurus",
    "Procyon lotor",
    "Salamandra",
    "Myrmecophaga tridactyla",
    "Vultur",
    "Macropodidae",
    "Xerus",
    "Abominable snowman",
    "Ictonyx striatus",
    "Elephantidae",
    "Tapirus terrestris",
    "Lemur catta",
    "Dromaius novaehollandiae",
    "Cygnus olor",
    "Camelidae",
    "Chinchilla lanigera",
    "Alces alces",
    "Cervus elaphus",
    "Capra aegagrus hircus",
    "Thylacinus cynocephalus",
    "Chelonia mydas",
    "Spheniscus demersus",
    "Pteropus",
    "Colobus guereza",
    "Puma concolor",
    "Didelphis virginiana",
    "Tursiops truncatus",
    "Castor fiber",
    "Equus quagga",
    "Dasyurus",
    "Sus scrofa",
    "Hyaenidae",
    "Lepus",
    "Phocoena phocoena",
    "Sirenia",
    "Gekkota",
    "Oncorhynchus mykiss",
    "Cyprinidae",
    "Eschrichtius robustus",
    "Loris",
    "Carcharhinus",
    "Scombridae",
    "Corvus corax",
    "Squalidae",
    "Strigiformes",
    "Bos mutus",
    "Equus grevyi",
    "Columbidae",
    "Psittacidae",
    "Psittacula krameri",
    "Eulemur",
    "Phalangeridae",
    "Notoryctemorphia",
    "Anseriformes",
    "Eubalaena",
    "Anser anser",
    "Vespertilionidae",
    "Anseriformes",
    "Cervidae",
    "Chiroptera",
    "Eutheria",
    "Rhinocerotidae",
    "Arctocephalus",
    "Bos primigenius",
    "Megalonychidae",
    "Cypriniformes",
    "Corvus brachyrhynchos",
    "Anser anser",
    "Cygnus atratus",
    "Felis silvestris catus",
    "Odocoileus virginianus",
    "Gorilla beringei",
    "Meles meles",
    "Cervus nippon",
    "Didelphis marsupialis",
    "Balaenoptera musculus",
    "Caiman crocodilus",
    "Stegostoma fasciatum",
    "Cygnus buccinator",
    "Equus africanus asinus",
    "Equus zebra zebra",
    "Stegostoma tigrinum",
    "Melopsittacus undulatus",
    "Cygnus cygnus",
    "Phocoena sinus",
    "Melursus ursinus",
    "Caretta caretta",
    "Ciconiiformes",
    "Viverridae",
    "Pogona vitticeps",
    "Ctenocephalides felis",
    "Bison bison",
    "Tetraodontidae",
    "Pagophilus groenlandicus",
    "Lagenorhynchus acutus",
    "Vombatus ursinus",
    "Sciuridae",
    "Elasmobranchii",
    "Alcelaphus buselaphus",
    "Ursidae",
    "Nyctereutes procyonoides",
    "Lama glama",
    "Orycteropus afer",
    "Pteropus vampyrus",
    "Mustela erminea",
    "Pogona barbata",
    "Antilocapra americana",
    "Lagenorhynchus obliquidens",
    "Dugong dugon",
    "Equus hemionus",
    "Dasypus novemcinctus",
    "Oryx leucoryx",
    "Lagenorhynchus albirostris",
    "Chlamydosaurus kingii",
    "Callithrix jacchus",
    "Chelydra serpentina",
    "Cervus canadensis",
    "Trichechus manatus",
    "Chinchilla chinchilla",
    "Gazella dama",
    "Dasyprocta",
    "Mustela nivalis",
    "Camelus ferus",
    "Coelacanth",
    "Delphinapterus leucas",
    "Echidna",
    "Melursus ursinus ursinus",
    "Equus asinus",
    "Sphaeramia nematoptera",
    "Aegypius monachus",
    "Orcinus orca",
    "Panthera onca",
    "Lemur",
    "Pongo",
    "Equus przewalskii",
    "Lemur fulvus",
    "Phoca",
    "Equus burchelli",
    "Tarsius",
    "Antilopinae",
    "Geochelone",
    "Panthera leo",
    "Phascolarctos",
    "Gallus",
    "Felis",
    "Equus quagga quagga",
    "Equus africanus",
    "Cervus",
    "Tachyglossidae",
    "Mellivora capensis",
    "Mustela",
    "Didelphimorphia",
    "Equus ferus",
    "Odobenus rosmarus",
    "Hylobates lar",
    "Erinaceinae",
    "Ceratotherium simum",
    "Galeopterus variegatus",
    "Leporidae",
    "Marmota monax",
    "Dasypus",
    "Vulpes",
    "Hippopotamus",
    "Canidae",
    "Perissodactyla",
    "Tragulidae",
    "Macropodidae",
    "Hominidae",
    "Lepidosauria",
    "Callorhinus ursinus",
    "Cervus elaphus",
    "Phasianidae",
    "Psittaculidae",
    "Lorisidae",
    "Macropodinae",
    "Notoryctidae",
    "Vespertilioninae",
    "Vespertilionidae",
    "Suidae",
    "Felidae",
    "Didelphidae",
    "Delphinidae",
    "Castoridae",
    "Felidae",
    "Cervidae",
    "Bos mutus",
    "Equus grevyi",
    "Anatidae",
    "Balaenopteridae",
    "Anatidae",
    "Vespertilionidae",
    "Anatidae",
    "Cervidae",
    "Chiroptera",
    "Mammalia",
    "Rhinocerotidae",
    "Otariidae",
    "Bovidae",
    "Phoxinus phoxinus",
    "Aves",
    "Ruminantia",
    "Dinosauria",
    "Falconiformes",
    "Mustelidae",
    "Panthera",
    "Dasypodidae",
    "Rodentia",
    "Artiodactyla",
    "Pinnipedia",
    "Chinchillidae",
    "Antilopinae",
    "Soricidae",
    "Camelidae",
    "Notoryctemorphia",
    "Pelecaniformes",
    "Cetacea",
    "Mustelidae",
    "Macropus",
    "Lar gibbon",
    "Erinaceidae",
    "Rhinocerotidae",
    "Pteropodidae",
    "Mustelidae",
    "Agamidae",
    "Felidae",
    "Antilocapridae",
    "Delphinidae",
    "Dugongidae",
    "Equus",
    "Dasypus",
    "Oryx",
    "Delphinidae",
    "Agamidae",
    "Callitrichidae",
    "Chelydridae",
    "Cervidae",
    "Trichechus",
    "Chinchillidae",
    "Gazella dama mhorr",
    "Dasyproctidae",
    "Mustelidae",
    "Camelidae",
    "Coelacanthiformes",
    "Delphinapterus",
    "Tachyglossus",
    "Melursus ursinus ursinus",
    "Equus africanus asinus",
    "Pterophyllum scalare",
    "Aegypius monachus",
    "Orcinus",
    "Panthera onca",
    "Lemuridae",
    "Pongo pygmaeus",
    "Equus przewalskii",
    "Lemur fulvus",
    "Phocidae",
    "Equus burchelli",
    "Tarsius tarsier",
    "Antilopinae",
    "Geochelone nigra",
    "Panthera leo",
    "Phascolarctos cinereus",
    "Gallus gallus domesticus",
    "Felis silvestris",
    "Equus quagga quagga",
    "Equus africanus",
    "Cervus elaphus",
    "Tachyglossidae",
    "Mellivora capensis",
    "Mustela nivalis",
    "Didelphimorphia",
    "Equus ferus",
    "Odobenus rosmarus",
    "Hylobates lar",
    "Erinaceinae",
    "Ceratotherium simum",
    "Galeopterus variegatus",
    "Leporidae",
    "Marmota monax",
    "Dasypus novemcinctus",
    "Vulpes vulpes",
    "Hippopotamus amphibius",
    "Canidae",
    "Perissodactyla",
    "Tragulidae",
    "Macropodidae",
    "Hominidae",
    "Lepidosauria",
    "Callorhinus ursinus",
    "Cervus elaphus",
    "Phasianidae",
    "Psittaculidae",
    "Lorisidae",
    "Macropodinae",
    "Notoryctidae",
    "Vespertilioninae",
    "Vespertilionidae",
    "Suidae",
    "Felidae",
    "Didelphidae",
    "Delphinidae",
    "Castoridae",
    "Felidae",
    "Cervidae",
    "Bos mutus",
    "Equus grevyi",
    "Anatidae",
    "Balaenopteridae",
    "Anatidae",
    "Vespertilionidae",
    "Anatidae",
    "Cervidae",
    "Chiroptera",
    "Mammalia",
    "Rhinocerotidae",
    "Otariidae",
    "Bovidae",
    "Phoxinus phoxinus",
    "Aves",
    "Ruminantia",
    "Dinosauria",
    "Falconiformes",
    "Mustelidae",
    "Panthera",
    "Dasypodidae",
    "Rodentia",
    "Artiodactyla",
    "Pinnipedia",
    "Chinchillidae",
    "Antilopinae",
    "Soricidae",
    "Camelidae",
    "Notoryctemorphia",
    "Pelecaniformes",
    "Cetacea",
    "Mustelidae",
    "Macropus",
    "Lar gibbon",
    "Erinaceidae",
    "Cervidae",
    "Rhincodontidae",
    "Ceratotheriidae",
    "Lemuridae",
    "Cheloniidae",
    "Spheniscidae",
    "Pteropodidae",
    "Cercopithecidae",
    "Puma concolor",
    "Phascolarctos cinereus",
    "Acinonyx jubatus",
    "Felidae",
    "Bubalus bubalis",
    "Camelus dromedarius",
    "Canis aureus",
    "Naja naja",
    "Formicidae",
    "Rana temporaria",
    "Iguana iguana",
    "Phascolarctos cinereus",
    "Lutra lutra",
    "Ovis aries",
    "Orcinus orca",
    "Panthera pardus",
    "Rattus norvegicus",
    "Talpa europaea",
    "Bos taurus",
    "Bos grunniens",
    "Balaenoptera physalus",
    "Astacidea",
    "Mustela putorius furo",
    "Hylobates lar",
    "Cricetinae",
    "Panthera onca",
    "Oryctolagus cuniculus",
    "Marmota monax",
    "Monodon monoceros",
    "Otariidae",
    "Ailuropoda melanoleuca",
    "Setonix brachyurus",
    "Procyon lotor",
    "Salamandra salamandra",
    "Myrmecophaga tridactyla",
    "Vultur gryphus",
    "Macropodidae",
    "Xerus",
    "Yeti",
    "Ictonyx striatus",
    "Elephantidae",
    "Tapirus terrestris",
    "Lemur catta",
    "Dromaius novaehollandiae",
    "Cygnus olor",
    "Camelidae",
    "Chinchilla lanigera",
    "Alces alces",
    "Cervus elaphus",
    "Capra aegagrus hircus",
    "Thylacinus cynocephalus",
    "Chelonia mydas",
    "Spheniscus demersus",
    "Pteropus",
    "Colobus guereza",
    "Puma concolor",
    "Didelphis virginiana",
    "Tursiops truncatus",
    "Castor fiber",
    "Equus quagga",
    "Dasyurus",
    "Sus scrofa",
    "Hyaenidae",
    "Lepus",
    "Phocoena phocoena",
    "Sirenia",
    "Gekkota",
    "Oncorhynchus mykiss",
    "Cyprinidae",
    "Eschrichtius robustus",
    "Loris",
    "Carcharhinus",
    "Scombridae",
    "Corvus corax",
    "Squalidae",
    "Strigiformes",
    "Bos mutus",
    "Equus grevyi",
    "Columbidae",
    "Psittacidae",
    "Psittacula krameri",
    "Eulemur",
    "Phalangeridae",
    "Notoryctemorphia",
    "Anseriformes",
    "Eubalaena",
    "Anser anser",
    "Vespertilionidae",
    "Anseriformes",
    "Cervidae",
    "Chiroptera",
    "Eutheria",
    "Rhinocerotidae",
    "Arctocephalus",
    "Bos primigenius",
    "Megalonychidae",
    "Cypriniformes",
    "Corvus brachyrhynchos",
    "Anser anser",
    "Cygnus atratus",
    "Felis silvestris catus",
    "Odocoileus virginianus",
    "Gorilla beringei",
    "Meles meles",
    "Cervus nippon",
    "Didelphis marsupialis",
    "Balaenoptera musculus",
    "Caiman crocodilus",
    "Stegostoma fasciatum",
    "Cygnus buccinator",
    "Equus africanus asinus",
    "Equus zebra zebra",
    "Stegostoma tigrinum",
    "Melopsittacus undulatus",
    "Cygnus cygnus",
    "Phocoena sinus",
    "Melursus ursinus",
    "Caretta caretta",
    "Ciconiiformes",
    "Viverridae",
    "Pogona vitticeps",
    "Ctenocephalides felis",
    "Bison bison",
    "Tetraodontidae",
    "Pagophilus groenlandicus",
    "Lagenorhynchus acutus",
    "Vombatus ursinus",
    "Sciuridae",
    "Elasmobranchii",
    "Alcelaphus buselaphus",
    "Ursidae",
    "Nyctereutes procyonoides",
    "Lama glama",
    "Orycteropus afer",
    "Pteropus vampyrus",
    "Mustela erminea",
    "Pogona barbata",
    "Antilocapra americana",
    "Lagenorhynchus obliquidens",
    "Dugong dugon",
    "Equus hemionus",
    "Dasypus novemcinctus",
    "Oryx leucoryx",
    "Lagenorhynchus albirostris",
    "Chlamydosaurus kingii",
    "Callithrix jacchus",
    "Chelydra serpentina",
    "Cervus canadensis",
    "Trichechus manatus",
    "Chinchilla chinchilla",
    "Gazella dama",
    "Dasyprocta",
    "Mustela nivalis",
    "Camelus ferus",
    "Coelacanth",
    "Delphinapterus leucas",
    "Echidna",
    "Melursus ursinus ursinus",
    "Equus asinus",
    "Sphaeramia nematoptera",
    "Aegypius monachus",
    "Orcinus orca",
    "Panthera onca",
    "Lemur",
    "Pongo",
    "Equus przewalskii",
    "Lemur fulvus",
    "Phoca",
    "Equus burchelli",
    "Tarsius",
    "Antilopinae",
    "Geochelone",
    "Panthera leo",
    "Phascolarctos",
    "Gallus",
    "Felis",
    "Equus quagga quagga",
    "Equus africanus",
    "Cervus",
    "Tachyglossidae",
    "Mellivora capensis",
    "Mustela",
    "Didelphimorphia",
    "Equus ferus",
    "Odobenus rosmarus",
    "Hylobates lar",
    "Erinaceinae",
    "Ceratotherium simum",
    "Galeopterus variegatus",
    "Leporidae",
    "Marmota monax",
    "Dasypus",
    "Vulpes",
    "Hippopotamus",
    "Canidae",
    "Perissodactyla",
    "Tragulidae",
    "Macropodidae",
    "Hominidae",
    "Lepidosauria",
    "Callorhinus ursinus",
    "Cervus elaphus",
    "Phasianidae",
    "Psittaculidae",
    "Lorisidae",
    "Macropodinae",
    "Notoryctidae",
    "Vespertilioninae",
    "Vespertilionidae",
    "Suidae",
    "Felidae",
    "Didelphidae",
    "Delphinidae",
    "Castoridae",
    "Felidae",
    "Cervidae",
    "Bos mutus",
    "Equus grevyi",
    "Anatidae",
    "Balaenopteridae",
    "Anatidae",
    "Vespertilionidae",
    "Anatidae",
    "Cervidae",
    "Chiroptera",
    "Mammalia",
    "Rhinocerotidae",
    "Otariidae",
    "Bovidae",
    "Phoxinus phoxinus",
    "Aves",
    "Ruminantia",
    "Dinosauria",
    "Falconiformes",
    "Mustelidae",
    "Panthera",
    "Dasypodidae",
    "Rodentia",
    "Artiodactyla",
    "Pinnipedia",
    "Chinchillidae",
    "Antilopinae",
    "Soricidae",
    "Camelidae",
    "Notoryctemorphia",
    "Pelecaniformes",
    "Cetacea",
    "Mustelidae",
    "Macropus",
    "Lar gibbon",
    "Erinaceidae",
    "Cervidae",
    "Rhincodontidae",
    "Ceratotheriidae",
    "Lemuridae",
    "Cheloniidae",
    "Spheniscidae",
    "Pteropodidae",
    "Cercopithecidae",
    "Puma concolor",
    "Phascolarctos cinereus",
    "Acinonyx jubatus",
    "Felidae",
    "Bubalus bubalis",
    "Camelus dromedarius",
    "Canis aureus",
    "Naja naja",
    "Formicidae",
    "Rana temporaria",
    "Iguana iguana",
    "Phascolarctos cinereus",
    "Lutra lutra",
    "Ovis aries",
    "Orcinus orca",
    "Panthera pardus",
    "Rattus norvegicus",
    "Talpa europaea",
    "Bos taurus",
    "Bos grunniens",
    "Balaenoptera physalus",
    "Astacidea",
    "Mustela putorius furo",
    "Hylobates lar",
    "Cricetinae",
    "Panthera onca",
    "Oryctolagus cuniculus",
    "Marmota monax",
    "Monodon monoceros",
    "Otariidae",
    "Ailuropoda melanoleuca",
    "Setonix brachyurus",
    "Procyon lotor",
    "Salamandra salamandra",
    "Myrmecophaga tridactyla",
    "Vultur gryphus",
    "Macropodidae",
    "Xerus",
    "Yeti",
    "Ictonyx striatus",
    "Elephantidae",
    "Tapirus terrestris",
    "Lemur catta",
    "Dromaius novaehollandiae",
    "Cygnus olor",
    "Camelidae",
    "Chinchilla lanigera",
    "Alces alces",
    "Cervus elaphus",
    "Capra aegagrus hircus",
    "Thylacinus cynocephalus",
    "Chelonia mydas",
    "Spheniscus demersus",
    "Pteropus",
    "Colobus guereza",
    "Puma concolor",
    "Didelphis virginiana",
    "Tursiops truncatus",
    "Castor fiber",
    "Equus quagga",
    "Dasyurus",
    "Sus scrofa",
    "Hyaenidae",
    "Lepus",
    "Phocoena phocoena",
    "Sirenia",
    "Gekkota",
    "Oncorhynchus mykiss",
    "Cyprinidae",
    "Eschrichtius robustus",
    "Loris",
    "Carcharhinus",
    "Scombridae",
    "Corvus corax",
    "Squalidae",
    "Strigiformes",
    "Bos mutus",
    "Equus grevyi",
    "Columbidae",
    "Psittacidae",
    "Psittacula krameri",
    "Eulemur",
    "Phalangeridae",
    "Notoryctemorphia",
    "Anseriformes",
    "Eubalaena",
    "Anser anser",
    "Vespertilionidae",
    "Anseriformes",
    "Cervidae",
    "Chiroptera",
    "Eutheria",
    "Rhinocerotidae",
    "Arctocephalus",
    "Bos primigenius",
    "Megalonychidae",
    "Cypriniformes",
    "Corvus brachyrhynchos",
    "Anser anser",
    "Cygnus atratus",
    "Felis silvestris catus",
    "Odocoileus virginianus",
    "Gorilla beringei",
    "Meles meles",
    "Cervus nippon",
    "Didelphis marsupialis",
    "Balaenoptera musculus",
    "Caiman crocodilus",
    "Stegostoma fasciatum",
    "Cygnus buccinator",
    "Equus africanus asinus",
    "Equus zebra zebra",
    "Stegostoma tigrinum",
    "Melopsittacus undulatus",
    "Cygnus cygnus",
    "Phocoena sinus",
    "Melursus ursinus",
    "Caretta caretta",
    "Ciconiiformes",
    "Viverridae",
    "Pogona vitticeps",
    "Ctenocephalides felis",
    "Bison bison",
    "Tetraodontidae",
    "Pagophilus groenlandicus",
    "Lagenorhynchus acutus",
    "Vombatus ursinus",
    "Sciuridae",
    "Elasmobranchii",
    "Alcelaphus buselaphus",
    "Ursidae",
    "Nyctereutes procyonoides",
    "Lama glama",
    "Orycteropus afer",
    "Pteropus vampyrus",
    "Mustela erminea",
    "Pogona barbata",
    "Antilocapra americana",
    "Lagenorhynchus obliquidens",
    "Dugong dugon",
    "Equus hemionus",
    "Dasypus novemcinctus",
    "Oryx leucoryx",
    "Lagenorhynchus albirostris",
    "Chlamydosaurus kingii",
    "Callithrix jacchus",
    "Chelydra serpentina",
    "Cervus canadensis",
    "Trichechus manatus",
    "Chinchilla chinchilla",
    "Gazella dama",
    "Dasyprocta",
    "Mustela nivalis",
    "Pristidae",
    "Prionailurus bengalensis",
    "Odocoileus hemionus",
    "Cygnus columbianus",
    "Bubo bubo",
    "Equus ferus przewalskii",
    "Cathartidae",
    "Ammodytes tobianus",
    "Phoca vitulina",
    "Dasyatis",
    "Castor canadensis",
    "Scolopacidae",
    "Pteronura brasiliensis",
    "Lepus europaeus",
    "Heterocephalus glaber",
    "Odocoileus",
    "Salvelinus fontinalis",
    "Equus caballus",
    "Ovis orientalis musimon",
    "Oryx gazella",
    "Callithrix penicillata",
    "Colobinae",
    "Eurasian magpie",
    "Equus burchelli boehmi",
    "Aegypius tracheliotus",
    "Mustela nivalis vulgaris",
    "Ciconia ciconia",
    "Lepus timidus",
    "Chelonia",
    "Didelphidae",
    "Balaenoptera",
    "Lemuridae",
    "Pongo abelii",
    "Procyon",
    "Frog",
    "Iguanidae",
    "Viverridae",
    "Ardeidae",
    "Cervus unicolor",
    "Mephitis mephitis",
    "Equus kiang",
    "Perameles nasuta",
    "Fulmarus glacialis",
    "Gulo gulo",
    "Pteropodidae",
    "Columbidae",
    "Cervus canadensis nelsoni",
    "Nasalis larvatus",
    "Mustelinae",
    "Mammuthus",
    "Echeneis naucrates",
    "Gorilla gorilla",
    "Suidae",
    "Cervus elaphus",
    "Macropodinae",
    "Alouatta",
    "Tetraodontidae",
    "Mustela lutreola",
    "Ailurus",
    "Lama",
    "Phasianus colchicus",
    "Vulpes vulpes",
    "Mustelinae",
    "Tarsius tarsier",
    "Gorilla gorilla gorilla",
    "Hippopotamus amphibius",
    "Trichechus",
    "Lemur catta",
    "Panthera tigris",
    "Petauridae",
    "Equus grevyi grevyi",
    "Felidae",
    "Columba livia",
    "Cygnus melancoryphus",
    "Carcharodon carcharias",
    "Papio hamadryas",
    "Papio cynocephalus",
    "Bos grunniens grunniens",
    "Sus scrofa domesticus",
    "Perissodactyla",
    "Papio",
    "Vespa crabro",
    "Bos indicus",
    "Vespertilio murinus",
    "Gorilla gorilla diehli",
    "Naja",
    "Lissotriton vulgaris",
    "Mustela vison",
    "Thylacine",
    "Camelus",
    "Delphinus delphis",
    "Tursiops",
    "Melursus",
    "Equus kiang polyodon",
    "Chelonia mydas mydas",
    "Erinaceidae",
    "Panthera pardus orientalis",
    "Dugong",
    "Myrmecophagidae",
    "Lutra",
    "Mustela nivalis nivalis",
    "Ursus americanus",
    "Zalophus californianus",
    "Elephant seal",
    "Procyonidae",
    "Equus burchelli",
    "Urocyon cinereoargenteus",
    "Ailuropoda",
    "Mustela putorius",
    "Macropus rufus",
    "Vulpes velox",
    "Cervidae",
    "Alopex lagopus",
    "Castoridae",
    "Mustela nivalis vulgaris",
    "Odobenidae",
    "Mustela",
    "Phoca largha",
    "Chlamydosaurus",
    "Anatidae",
    "Felidae",
    "Balaenoptera acutorostrata",
    "Thalasseus maximus",
    "Scombridae",
    "Nasua nasua",
    "Pteropus giganteus",
    "Tursiops truncatus truncatus",
    "Alopex",
    "Canis lupus familiaris",
    "Geochelone gigantea",
    "Equus africanus somaliensis",
    "Dugong dugon",
    "Castor canadensis canadensis",
    "Marmota",
    "Naja haje",
    "Panthera onca",
    "Acrocephalus arundinaceus",
    "Panthera tigris sumatrae",
    "Naja kaouthia",
    "Mustela nigripes",
    "Eumetopias jubatus",
    "Macropodidae",
    "Macropus fuliginosus",
    "Equus asinus asinus",
    "Mustela putorius putorius",
    "Mustela altaica",
    "Mustela erminea aestiva",
    "Mustela erminea hibernica",
    "Mustela erminea arctica",
    "Mustela frenata",
    "Phascolarctos cinereus adustus",
    "Chiroptera",
    "Sirenidae",
    "Odobenus",
    "Eudyptes chrysolophus",
    "Carcharhinus leucas",
    "Phalacrocorax carbo",
    "Elephantidae",
    "Alcelaphus",
    "Bison bison bison",
    "Ammodytes",
    "Vulpes ferrilata",
    "Phocoenidae",
    "Equus kiang kiang",
    "Ursus maritimus",
    "Alces",
    "Mustelidae",
    "Lemuridae",
    "Callithrix",
    "Ara ararauna",
    "Chelydra",
    "Equus grevyi pygmaeus",
    "Echeneis",
    "Odobenidae",
    "Gulo",
    "Mustela nigripes",
    "Gorilla",
    "Vespertilionidae",
    "Dromaius",
    "Cygnus",
    "Phascolarctos cinereus cinereus",
    "Hyaena",
    "Cetacea",
    "Globicephala melas",
    "Eulemur fulvus",
    "Dendrolagus",
    "Mustela putorius furo",
    "Haliaeetus leucocephalus",
    "Ara macao",
    "Hippopotamidae",
    "Equus africanus africanus",
    "Ursus arctos",
    "Castor",
    "Mustela",
    "Eudyptes chrysolophus",
    "Gazella",
    "Erinaceus europaeus",
    "Panthera leo persica",
    "Equus burchellii boehmi",
    "Acinonyx jubatus jubatus",
    "Dugongidae",
    "Balaenoptera physalus",
    "Scomber scombrus",
    "Haliaeetus albicilla",
    "Vespertilioninae",
    "Hippocampus hippocampus",
    "Mustela erminea nivalis",
    "Elephantidae",
    "Mustela nigripes nigripes",
    "Mustela erminea aestiva",
    "Mustela erminea hibernica",
    "Mustela erminea arctica",
    "Puma",
    "Chlamyphoridae",
    "Felis",
    "Procyon",
    "Castoridae",
    "Castor canadensis",
    "Phoca",
    "Pteropus",
    "Callithrix",
    "Mustela putorius",
    "Ursus",
    "Pogona",
    "Equus",
    "Cygnus",
    "Macropus",
    "Panthera",
    "Balaenoptera",
    "Tursiops",
    "Acinonyx",
    "Lemur",
    "Hippopotamus",
    "Sphyrnidae",
    "Delphinidae",
    "Phocoena",
    "Ardeidae",
    "Cervus",
    "Panthera tigris",
    "Odobenus rosmarus",
    "Phasianus",
    "Vulpes",
    "Thalasseus",
    "Eudyptes",
    "Dendrolagus",
    "Lagenorhynchus",
    "Odobenidae",
    "Lissotriton",
    "Cyprinidae",
    "Perissodactyla",
    "Globicephala",
    "Cervidae",
    "Phalacrocorax",
    "Equus ferus",
    "Equus hemionus hemionus",
    "Gorilla beringei beringei",
    "Lorisidae",
    "Chelydra serpentina",
    "Callithrix jacchus",
    "Panthera pardus orientalis",
    "Mustela putorius furo",
    "Phocoena phocoena",
    "Elephantidae",
    "Hippopotamidae",
    "Scombridae",
    "Cygnus olor",
    "Castor fiber",
    "Cervus elaphus",
    "Odobenus rosmarus rosmarus",
    "Macropus rufus",
    "Panthera onca",
    "Mustela erminea",
    "Eulemur fulvus",
    "Cervus canadensis",
    "Lepus",
    "Delphinus delphis",
    "Equus quagga",
    "Gulo gulo",
    "Mustela putorius putorius",
    "Hyaena hyaena",
    "Ursus arctos",
    "Papio",
    "Pteronura brasiliensis",
    "Haliaeetus leucocephalus",
    "Oryctolagus cuniculus",
    "Alces alces",
    "Lama glama",
    "Odobenidae",
    "Mustela vison",
    "Mustela nigripes",
    "Erinaceus europaeus",
    "Ciconiidae",
    "Elephas maximus",
    "Anas platyrhynchos",
    "Naja naja",
    "Phasianidae",
    "Mustela nivalis",
    "Pteropus vampyrus",
    "Castor canadensis",
    "Panthera leo",
    "Equus africanus",
    "Mustela erminea",
    "Equus grevyi",
    "Gazella dama",
    "Dasyprocta",
    "Sphyrnidae",
    "Balaenoptera musculus",
    "Trichechus manatus",
    "Ursus maritimus",
    "Papio hamadryas",
    "Papio cynocephalus",
    "Papio ursinus",
    "Macropus robustus",
    "Gorilla gorilla",
    "Phocoena phocoena",
    "Hippopotamus amphibius",
    "Tursiops truncatus",
    "Panthera pardus",
    "Mustela putorius",
    "Lepus europaeus",
    "Equus asinus",
    "Lemur catta",
    "Alopex lagopus",
    "Cygnus columbianus",
    "Phoca vitulina",
    "Haliaeetus albicilla",
    "Ailuropoda melanoleuca",
    "Equus ferus przewalskii",
    "Acinonyx jubatus",
    "Bos taurus",
    "Sus scrofa",
    "Felis silvestris",
    "Canis lupus",
    "Oryx gazella",
    "Equus zebra",
    "Camelus dromedarius",
    "Phascolarctos cinereus",
    "Phocoenidae",
    "Mustela erminea",
    "Chlamyphoridae",
    "Alcelaphus buselaphus",
    "Erinaceidae",
    "Thalasseus sandvicensis",
    "Lepus timidus",
    "Anser anser",
    "Cervus nippon",
    "Viverridae",
    "Mephitis mephitis",
    "Equus kiang",
    "Equus grevyi",
    "Procyonidae",
    "Procyon lotor",
    "Odobenus rosmarus",
    "Sirenidae",
    "Tursiops truncatus",
    "Lemuridae",
    "Echeneis naucrates",
    "Papio papio",
    "Papio anubis",
    "Bos primigenius",
    "Cypriniformes",
    "Corvus brachyrhynchos",
    "Didelphis marsupialis",
    "Caiman crocodilus",
    "Stegostoma fasciatum",
    "Cygnus buccinator",
    "Equus africanus asinus",
    "Equus zebra zebra",
    "Stegostoma tigrinum",
    "Melopsittacus undulatus",
    "Cygnus cygnus",
    "Phocoena sinus",
    "Melursus ursinus",
    "Caretta caretta",
    "Ciconiiformes",
    "Viverridae",
    "Pogona vitticeps",
    "Ctenocephalides felis",
    "Bison bison",
    "Tetraodontidae",
    "Pagophilus groenlandicus",
    "Lagenorhynchus acutus",
    "Vombatus ursinus",
    "Sciuridae",
    "Elasmobranchii",
    "Alcelaphus buselaphus",
    "Ursidae",
    "Nyctereutes procyonoides",
    "Lama glama",
    "Ailurus fulgens",
    "Ammodytes marinus",
    "Canis lupus dingo",
    "Lepus americanus",
    "Urocyon cinereoargenteus",
    "Acinonyx jubatus",
    "Erinaceus europaeus",
    "Felis catus",
    "Camelus bactrianus",
    "Delphinidae",
    "Mustela erminea",
    "Mustela erminea",
    "Hippocampus",
    "Equus africanus",
    "Phasianus colchicus",
    "Vulpes vulpes",
    "Mustela",
    "Eudyptes chrysolophus",
    "Balaenoptera acutorostrata",
    "Thalasseus maximus",
    "Scombridae",
    "Nasua nasua",
    "Pteropus giganteus",
    "Tursiops truncatus truncatus",
    "Alopex",
    "Canis lupus familiaris",
    "Geochelone gigantea",
    "Equus africanus somaliensis",
    "Dugong dugon",
    "Castor canadensis canadensis",
    "Marmota",
    "Naja haje",
    "Panthera onca",
    "Acrocephalus arundinaceus",
    "Panthera tigris sumatrae",
    "Naja kaouthia",
    "Mustela nigripes",
    "Eumetopias jubatus",
    "Macropodidae",
    "Macropus fuliginosus",
    "Equus asinus asinus",
    "Mustela putorius putorius",
    "Mustela altaica",
    "Mustela erminea aestiva",
    "Mustela erminea hibernica",
    "Mustela erminea arctica",
    "Mustela frenata",
    "Phascolarctos cinereus adustus",
    "Chiroptera",
    "Sirenidae",
    "Odobenus",
    "Eudyptes chrysolophus",
    "Carcharhinus leucas",
    "Phalacrocorax carbo",
    "Elephantidae",
    "Alcelaphus",
    "Bison bison bison",
    "Ammodytes",
    "Vulpes ferrilata",
    "Phocoenidae",
    "Equus kiang kiang",
    "Ursus maritimus",
    "Alces",
    "Mustelidae",
    "Lemuridae",
    "Callithrix",
    "Ara ararauna",
    "Chelydra",
    "Equus grevyi pygmaeus",
    "Echeneis",
    "Odobenidae",
    "Gulo",
    "Mustela nigripes",
    "Gorilla",
    "Vespertilionidae",
    "Dromaius",
    "Cygnus",
    "Phascolarctos cinereus cinereus",
    "Hyaena",
    "Cetacea",
    "Globicephala",
    "Eulemur fulvus",
    "Dendrolagus",
    "Mustela putorius furo",
    "Haliaeetus leucocephalus",
    "Ara macao",
    "Hippopotamidae",
    "Equus africanus africanus",
    "Ursus arctos",
    "Castor",
    "Mustela",
    "Eudyptes chrysolophus",
    "Gazella",
    "Erinaceus europaeus",
    "Panthera leo persica",
    "Equus burchellii boehmi",
    "Acinonyx jubatus jubatus",
    "Dugongidae",
    "Balaenoptera physalus",
    "Scomber scombrus",
    "Haliaeetus albicilla",
    "Vespertilioninae",
    "Hippocampus hippocampus",
    "Mustela erminea nivalis",
    "Elephantidae",
    "Mustela nigripes nigripes",
    "Mustela erminea aestiva",
    "Mustela erminea hibernica",
    "Mustela erminea arctica",
    "Puma",
    "Chlamyphoridae",
    "Felis",
    "Procyon",
    "Castoridae",
    "Castor canadensis",
    "Phoca",
    "Pteropus",
    "Callithrix",
    "Mustela putorius",
    "Ursus",
    "Pogona",
    "Equus",
    "Cygnus",
    "Macropus",
    "Panthera",
    "Balaenoptera",
    "Tursiops",
    "Acinonyx",
    "Lemur",
    "Hippopotamus",
    "Sphyrnidae",
    "Delphinidae",
    "Phocoena",
    "Ardeidae",
    "Cervus",
    "Panthera tigris",
    "Odobenus rosmarus",
    "Phasianus",
    "Vulpes",
    "Thalasseus",
    "Eudyptes",
    "Dendrolagus",
    "Lagenorhynchus",
    "Odobenidae",
    "Lissotriton",
    "Cyprinidae",
    "Perissodactyla",
    "Globicephala",
    "Cervidae",
    "Phalacrocorax",
    "Equus ferus",
    "Equus hemionus hemionus",
    "Gorilla beringei beringei",
    "Lorisidae",
    "Chelydra serpentina",
    "Callithrix jacchus",
    "Panthera pardus orientalis",
    "Mustela putorius furo",
    "Phocoena phocoena",
    "Elephantidae",
    "Hippopotamidae",
    "Scombridae",
    "Cygnus olor",
    "Castor fiber",
    "Cervus elaphus",
    "Odobenus rosmarus rosmarus",
    "Macropus rufus",
    "Panthera onca",
    "Mustela erminea",
    "Eulemur fulvus",
    "Cervus canadensis",
    "Lepus",
    "Delphinus delphis",
    "Equus quagga",
    "Gulo gulo",
    "Mustela putorius putorius",
    "Hyaena hyaena",
    "Ursus arctos",
    "Papio",
    "Pteronura brasiliensis",
    "Haliaeetus leucocephalus",
    "Oryctolagus cuniculus",
    "Alces alces",
    "Lama glama",
    "Odobenidae",
    "Mustela vison",
    "Mustela nigripes",
    "Erinaceus europaeus",
    "Ciconiidae",
    "Elephas maximus",
    "Anas platyrhynchos",
    "Naja naja",
    "Phasianidae",
    "Mustela nivalis",
    "Pteropus vampyrus",
    "Castor canadensis",
    "Panthera leo",
    "Equus africanus",
    "Mustela ermine",
];
export const plantsLatinNames = [
    "Abelia",
    "Abelmoschus esculentus",
    "Abies",
    "Abutilon",
    "Acacia dealbata",
    "Acacia deanei",
    "Acanthus mollis",
    "Acanthus spinosus",
    "Acer",
    "Acer palmatum",
    "Acer pseudoplatanus",
    "Achillea",
    "Achillea filipendulina",
    "Acidanthera murielae",
    "Acmella oleracea",
    "Aconitum",
    "Acorus gramineus",
    "Acroclinium",
    "Actaea",
    "Actinidia",
    "Actinidia arguta",
    "Adansonia",
    "Adenium obesum",
    "Adiantum",
    "Adonis aestivalis",
    "Aechmea",
    "Aeonium",
    "Aesculus",
    "Aesculus parviflora",
    "Agapanthus",
    "Agastache",
    "Agathea caelestis",
    "Agave",
    "Aglaonema",
    "Ajania pacifica",
    "Ajuga",
    "Akebia",
    "Albizia",
    "Alcea",
    "Alchemilla",
    "Allium",
    "Allium cepa",
    "Allium cepa var. proliferum",
    "Allium porrum",
    "Allium sativum",
    "Allium schoenoprasum",
    "Allium ursinum",
    "Alnus",
    "Aloe",
    "Aloysia triphylla",
    "Alpinia purpurata",
    "Alstroemeria",
    "Althea officinalis",
    "Alyssum",
    "Amaranthus",
    "Amelanchier",
    "Amicia zygomeris",
    "Ammi",
    "Ampelodesmos mauritanicus",
    "Amsonia",
    "Anacyclus pyrethrum var. depressus",
    "Anagallis monelli",
    "Ananas",
    "Anaphalis margaritacea",
    "Anchusa",
    "Andromeda polifolia",
    "Anemone blanda",
    "Anemone coronaria",
    "Anemone hupehensis",
    "Anethum",
    "Anigozanthos rufus",
    "Anisodontea capensis",
    "Anthemis",
    "Anthriscus",
    "Anthriscus sylvestris",
    "Anthurium",
    "Antirrhinum majus",
    "Apios americana",
    "Apium graveolens",
    "Aptenia cordifolia",
    "Aquilegia",
    "Arabis",
    "Araucaria araucana",
    "Araucaria heterophylla",
    "Araujia sericifera",
    "Arbutus",
    "Arisaema",
    "Aristolochia macrophylla",
    "Arnica montana",
    "Artemisia",
    "Artemisia abrotanum",
    "Artemisia dracunculus",
    "Arthropodium cirrhatum",
    "Aruncus",
    "Arundo donax",
    "Asarum",
    "Asclepias tuberosa",
    "Ascocenda",
    "Asimina triloba",
    "Aspidistra",
    "Asplenium scolopendrium",
    "Astelia",
    "Aster",
    "Astilbe",
    "Astragalus membranaceus",
    "Astrancia",
    "Atriplex",
    "Atriplex halimus",
    "Aubrieta",
    "Aucuba",
    "Azalea japonica",
    "Azara microphylla",
    "Azorella trifurcata",
    "Ballota pseudodictamnus",
    "Balsamita major",
    "Bambusa",
    "Baptisia australis",
    "Begonia maculata",
    "Begonia rex-cultorum",
    "Begonia semperflorens",
    "Bellis",
    "Beloperone guttata",
    "Berberidopsis corallina",
    "Berberis",
    "Bergenia",
    "Beta vulgaris",
    "Betula",
    "Bignonia capreolata",
    "Billardiera heterophylla",
    "Blechnum spicant",
    "Boccania cordata",
    "Boehmeria",
    "Boltonia",
    "Borago",
    "Boronia crenulata",
    "Boronia heterophylla",
    "Bougainvillea",
    "Brachyglottis monroi",
    "Brachyscome",
    "Brassada",
    "Brassia",
    "Brassica oleracea",
    "Brassica oleracea botrytis var. cymosa",
    "Brassica rapa japonica",
    "Brighamia insignis",
    "Briza",
    "Briza maxima",
    "Briza media",
    "Brunnera",
    "Buddleja",
    "Bulbine frutescens",
    "Buxus",
    "Caesalpinia gilliesii",
    "Caladium",
    "Calamagrostis",
    "Calceolaria",
    "Calibrachoa",
    "Callistemon",
    "Callistephus chinensis",
    "Calluna",
    "Calocephalus brownii",
    "Calycanthus floridus",
    "Camassia",
    "Camellia",
    "Campanula",
    "Campanula rapunculus",
    "Campsis",
    "Canna",
    "Capsicum",
    "Cardamine hirsuta",
    "Carex",
    "Carica papaya",
    "Carissa macrocarpa",
    "Carpinus",
    "Carpobrotus",
    "Carum carvi",
    "Carya illinoinensis",
    "Cassia corymbosa",
    "Castanea",
    "Catalpa",
    "Catharanthus roseus",
    "Ceanothus",
    "Cedrela sinensis",
    "Cedrus",
    "Ceiba speciosa",
    "Celosia argentea",
    "Centaurea",
    "Centranthus ruber",
    "Cerastium tomentosum",
    "Cercidiphyllum japonicum",
    "Cereus hildmannianus",
    "Cerinthe major purpurascens",
    "Ceropegia woodii",
    "Chaenomeles",
    "Chaerophyllum bulbosum",
    "Chamaedorea",
    "Chamaemelum nobile",
    "Chamaerops humilis",
    "Chasmanthe floribunda",
    "Cheiranthus cheiri",
    "Chelone lyonii",
    "Chelone obliqua",
    "Chenopodium bonus-henricus",
    "Chionodoxa",
    "Chitalpa tashkentensis",
    "Choisya ternata",
    "Chorisia speciosa",
    "Choysia ternata",
    "Chrysanthemum",
    "Chrysanthemum coccineum",
    "Cicer arietinum",
    "Cichorium",
    "Cichorium endivia var. latifolium",
    "Cissus rhombifolia",
    "Cistus",
    "Citrullus lanatus",
    "Citrus aurantiifolia",
    "Citrus hystrix",
    "Citrus juno",
    "Citrus latifolia",
    "Citrus limon",
    "Citrus sinensis",
    "Citrus x meyeri",
    "Citrus x paradisi",
    "Clatteya",
    "Claytonia perfoliata",
    "Clematis",
    "Clematis armandii",
    "Clematis montana",
    "Clematis texensis",
    "Cleome",
    "Clerodendron",
    "Clethra alnifolia",
    "Clethra barbinervis",
    "Clianthus puniceus",
    "Clinopodium douglasii",
    "Clivia",
    "Clusia",
    "Cobaea scandens",
    "Cocos nucifera",
    "Codiaeum",
    "Coffea arabica",
    "Colchicum",
    "Colocasia esculenta",
    "Colutea arborescens",
    "Commelina tuberosa",
    "Convollaria majalis",
    "Convolvulus tricolor",
    "Coreopsis",
    "Coriandrum sativum",
    "Cornus",
    "Cornus florida",
    "Corokia cotoneaster",
    "Coronilla",
    "Corydalis",
    "Corylopsis",
    "Corylus avellana",
    "Cosmos",
    "Cotoneaster",
    "Crambe maritima",
    "Craspedia",
    "Crassula",
    "Crataegus",
    "Crinodendron hookerianum",
    "Crinum",
    "Crocosmia",
    "Crocus",
    "Crocus ancyrensis",
    "Ctenanthe setosa",
    "Cucumis anguria",
    "Cucumis melo",
    "Cucumis sativus",
    "Cucurbita maxima",
    "Cupressocyparis leylandii",
    "Cupressus",
    "Cupressus macrocarpa",
    "Curcurbita",
    "Curcurbita pepo",
    "Cycas",
    "Cyclamen coum",
    "Cyclamen hederifolium",
    "Cyclamen purpurascens",
    "Cydonia",
    "Cymbopogon citratus",
    "Cynara",
    "Cyperus",
    "Cytisus scoparius",
    "Daboecia",
    "Dahlia",
    "Dahlia imperialis",
    "Daphne mezereum",
    "Darwinia oxylepis",
    "Dasylirion",
    "Daucus carota",
    "Davallia fejeensis",
    "Davidia involucrata",
    "Delphinium",
    "Deschampsia",
    "Deutzia",
    "Dianthus",
    "Dianthus barbatus",
    "Dianthus carthusianorum",
    "Diascia",
    "Dicentra eximia",
    "Dicentra spectabilis",
    "Dichelostemma multiflorum",
    "Dichondra repens",
    "Dichromena colorata",
    "Dierama pulcherrimum",
    "Digitalis",
    "Disporopsis pernyi",
    "Disporum",
    "Dodonea viscosa 'purpurea'",
    "Dolichos sesquipedalis",
    "Doronicum",
    "Dorycnium hirsutum",
    "Dracaena sanderiana",
    "Dregea sinensis",
    "Drimys aromatica",
    "Dypsis decaryi",
    "Echeveria",
    "Echium",
    "Edgeworthia chrysantha",
    "Elaeagnus angustifolia",
    "Eleagnus multiflora",
    "Elegia capensis",
    "Elsholtzia stauntonii",
    "Embothrium coccineum",
    "Enkianthus campanulatus",
    "Ensete ventricosum var. maurelii",
    "Epimedium",
    "Epiphyllum",
    "Equisetum fluviatile",
    "Equisetum hyemale",
    "Eragrostis",
    "Eranthis hyemalis",
    "Erica",
    "Erica arborea",
    "Eriobotrya japonica",
    "Eriostemon myrioporoïdes",
    "Erodium",
    "Eryngium",
    "Erysimum",
    "Erythrina crista-galli",
    "Erythronium",
    "Eschscholtzia californica",
    "Eucalyptus",
    "Eucomis",
    "Eucryphia",
    "Euodia daniellii var. hupehensis",
    "Euonymus",
    "Euonymus japonicus",
    "Eupatorium",
    "Eupatorium rugosum 'chocolate'",
    "Euphorbia",
    "Euphorbia griffithii",
    "Euphorbia pulcherrima",
    "Eutrema japonicum",
    "Fagopyrum cymosum",
    "Fagopyrum dibotrys",
    "Fagopyrum esculentum",
    "Fagus",
    "Fallopia baldschuanica",
    "Farfugium japonicum",
    "Fatsia japonica",
    "Fatsia polycarpa",
    "Felicia amelloides",
    "Festuca",
    "Ficinia truncata",
    "Ficoïde",
    "Ficus benghalensis",
    "Ficus benjamina",
    "Ficus carica",
    "Ficus microcarpa",
    "Ficus pumila",
    "Ficus repens",
    "Ficus retusa",
    "Filipendula rubra",
    "Fittonia",
    "Fockea edulis",
    "Foeniculum vulgare",
    "Foeniculum vulgare 'purpureum'",
    "Forsythia",
    "Fothergilla",
    "Fragaria",
    "Franklinia alatamaha",
    "Fraxinus excelsior",
    "Freesia",
    "Fuchsia",
    "Gaillardia",
    "Galanthus",
    "Galega officinalis",
    "Galium odoratum",
    "Galtonia candicans",
    "Gardenia",
    "Garrya elliptica",
    "Gaultheria",
    "Gaura",
    "Gelsemium sempervirens",
    "Geranium",
    "Geum",
    "Gillenia",
    "Ginkgo biloba",
    "Gladiolus",
    "Gladiolus callianthus",
    "Gloriosa superba var. rothschildiana",
    "Gomphrena globosa",
    "Gordlinia grandiflora",
    "Gossypium",
    "Graptopetalum",
    "Grevillea juniperina",
    "Griselinia littoralis",
    "Gunnera manicata",
    "Gynostemma pentaphyllum",
    "Habenaria radiata",
    "Haemanthus multiflorus",
    "Hakonechloa macra",
    "Halesia carolina",
    "Hardenbergia violacea",
    "Haworthia",
    "Hebe",
    "Hedera",
    "Hedychium",
    "Hedychium coronarium",
    "Helenium",
    "Helianthus annuus",
    "Helichrysum",
    "Heliconia",
    "Helictotrichon sempervirens",
    "Heliopsis",
    "Helleborus",
    "Hemerocallis",
    "Heptacodium miconioides",
    "Heptaleurum brassaia",
    "Hermodactylus tuberosa",
    "Hesperis matronalis",
    "Heuchera",
    "Hibanobambusa tranquillans",
    "Hibiscus esculentus",
    "Hibiscus moscheutos",
    "Hibiscus syriacus",
    "Hieracium aurantiacum",
    "Hippeastrum",
    "Hosta",
    "Houstonia caerulea",
    "Houttuynia cordata",
    "Hovenia dulcis",
    "Howea",
    "Hoya",
    "Hyacinthus",
    "Hydrangea",
    "Hymenocallis x festalis",
    "Ilex",
    "Ilex crenata",
    "Illicium floridanum",
    "Impatiens",
    "Indigofera heterantha",
    "Ipheion uniflorum",
    "Ipomea batatas",
    "Ipomoea",
    "Ipomoea batatas",
    "Iresine herbstii",
    "Iris",
    "Iris barbata",
    "Iris tuberosa",
    "Iris unguicularis",
    "Ismene x festalis",
    "Isodon longituba",
    "Isolepis cernua",
    "Itea ilicifolia",
    "Itea virginica",
    "Jasminum nudiflorum",
    "Jasminum officinale",
    "Jasminum sambac",
    "Juglans regia",
    "Juniperus",
    "Kalanchoe",
    "Kalimeris incisa",
    "Keiskea japonica",
    "Kerria japonica",
    "Kniphofia",
    "Koeleria glauca",
    "Koelreuteria paniculata",
    "Laburnum",
    "Lactuca",
    "Laelia",
    "Lagerstroemia",
    "Lamium",
    "Lantana",
    "Larix",
    "Laurier jaune",
    "Laurus nobilis",
    "Lavandula",
    "Lavatera",
    "Lavatera trimestris",
    "Leonotis leonurus",
    "Leontopodium alpinum",
    "Lepidium sativum",
    "Leptinella",
    "Lespedeza thunbergii",
    "Leucadendron",
    "Leucanthemum",
    "Leucanthemum x superbum",
    "Leucojum",
    "Leucophyllum frutescens",
    "Leucophyta brownii",
    "Leucothoe",
    "Lewisia",
    "Liatris",
    "Licuala grandis",
    "Ligularia",
    "Ligustrum",
    "Lilium",
    "Lilium martagon",
    "Lilium pardalinum",
    "Limnanthes douglasii",
    "Linum grandiflorum",
    "Lippia citrodora",
    "Lippia dulcis",
    "Lippia nodiflora",
    "Liriodendron tulipifera",
    "Liriope muscari",
    "Lithodora diffusa",
    "Lithops",
    "Lobelia",
    "Lomatia tinctoria",
    "Lonicera",
    "Lonicera caerulea",
    "Lonicera henryi",
    "Lophomyrtus x ralphii",
    "Lophospermum",
    "Ludisia discolor",
    "Luma apiculata",
    "Luma chequen",
    "Lunaria",
    "Lupinus",
    "Luzula",
    "Lychnis coronaria",
    "Lycianthes rantonnetii",
    "Lycoris radiata",
    "Lysimachia",
    "Lythrum salicaria",
    "Macleaya cordata",
    "Macleaya pomifera",
    "Magnolia",
    "Magnolia grandiflora",
    "Magnolia stellata",
    "Mahonia",
    "Malcolmia maritima",
    "Malus",
    "Malva",
    "Marrubium vulgare",
    "Matthiola incana",
    "Meconopsis betonicifolia",
    "Medicago arborea",
    "Melianthus major",
    "Melilotus",
    "Melissa",
    "Melothria scabra",
    "Mentha",
    "Mesembryanthemum crystallinum",
    "Metrosideros excelsa",
    "Michelia",
    "Millettia japonica",
    "Mimosa pudica",
    "Mimulus",
    "Mirabilis",
    "Miscanthus",
    "Miscanthus nepalensis",
    "Moltkia",
    "Momordica charantia",
    "Monarda",
    "Montia perfoliata",
    "Morina longifolia",
    "Moringa oleifera",
    "Morus",
    "Muehlenbeckia",
    "Muhlenbergia capillaris",
    "Murraya paniculata",
    "Musa",
    "Muscari",
    "Myosotis",
    "Myriophyllum aquaticum",
    "Myrsine africana",
    "Myrtus apiculata",
    "Myrtus chequen",
    "Myrtus luma",
    "Narcissus",
    "Nasturtium officinale",
    "Nectaroscordium siculum",
    "Nelumbo",
    "Nerine bowdenii",
    "Nerium oleander",
    "Nicandra physaloides",
    "Nicotiana",
    "Nigella damascena",
    "Nuphar",
    "Nuphar lutea",
    "Nymphea",
    "Nyssa sylvatica",
    "Ocimum",
    "Ocimum kilimandscharicum",
    "Oenothera",
    "Olea europea",
    "Oncidium",
    "Onychium japonicum",
    "Opuntia ficus-indica",
    "Orbea variegata",
    "Origanum majorana",
    "Origanum vulgare",
    "Osmoxylon lineare",
    "Osmunda regalis",
    "Oxalis articulata",
    "Oxalis deppei",
    "Oxalis tetraphylla",
    "Oxydendron arboreum",
    "Oxypetalum caeruleum",
    "Pachyphragma macrophyllum",
    "Pachysandra terminalis",
    "Paeonia",
    "Pandorea jasminoides",
    "Panicum virgatum",
    "Papaver croceum",
    "Papaver nudicaule",
    "Papaver orientale",
    "Papaver rhoeas",
    "Paris polyphylla",
    "Parrotia persica",
    "Parthenocissus",
    "Passiflora",
    "Patrinia",
    "Pavonia multiflora",
    "Pecteilis radiata",
    "Pelargonium",
    "Pennisetum glaucum",
    "Penstemon",
    "Pentas lanceolata",
    "Peperomia",
    "Pernettya",
    "Persicaria amplexicaulis",
    "Petasites",
    "Petroselinum",
    "Petunia",
    "Phacelia tanacetifolia",
    "Phalaenopsis",
    "Phalaris arundinacea",
    "Phaseolus",
    "Phaseolus coccineus",
    "Philotheca myoporoides",
    "Phlox",
    "Phoenix canariensis",
    "Phoenix roebelenii",
    "Photinia",
    "Phragmipedium",
    "Phuopsis stylosa",
    "Phygelius capensis",
    "Phyllostachys",
    "Physalis alkekengi",
    "Physalis peruviana",
    "Physostegia virginiana",
    "Picea",
    "Pilea peperomioides",
    "Pileostegia viburnoides",
    "Pilosella aurantiaca",
    "Pimelea ferruginea",
    "Pinus",
    "Pistachier",
    "Pistacia lentiscus",
    "Pittosporum tenuifolium",
    "Pittosporum tobira",
    "Platanus",
    "Platycerium",
    "Platycodon grandiflora",
    "Plectranthus australis",
    "Pleione",
    "Plumbago auriculata",
    "Polianthes tuberosa",
    "Polygonatum",
    "Polygonum baldschuanicum",
    "Polyscias",
    "Populus",
    "Populus tremula",
    "Potentilla",
    "Primula",
    "Primula juliae",
    "Primula veris",
    "Prostanthera cuneata",
    "Protea",
    "Prunus avium",
    "Prunus cerasus",
    "Prunus domestica",
    "Prunus domestica n-subsp. italica",
    "Prunus laurocerasus",
    "Prunus lusitanica",
    "Prunus mume",
    "Prunus padus",
    "Prunus persica",
    "Prunus spinosa",
    "Prunus tomentosa",
    "Prunus triloba",
    "Pteris",
    "Pterostyrax",
    "Pulmonaria",
    "Pulsatilla vulgaris",
    "Puschkinia 'libanotica'",
    "Pyrethrum roseum",
    "Pyrus",
    "Pyrus communis",
    "Quercus",
    "Quercus ilex",
    "Quercus suber",
    "Rabdosia longituba",
    "Ranunculus",
    "Raoulia",
    "Raphanus sativus",
    "Raphanus sativus niger",
    "Raphanus sativus var. longipinnatus",
    "Reinwardtia indica",
    "Reseda",
    "Rhaphiolepis",
    "Rheum rhaponticum",
    "Rhipsalis",
    "Rhodochiton atrosanguineus",
    "Rhododendron",
    "Rhododendron obtusum",
    "Rhus typhina",
    "Rhynchospora colorata",
    "Ribes",
    "Ribes nigrum",
    "Robinia pseudoacacia",
    "Rodgersia",
    "Romneya coulteri",
    "Rosa",
    "Rosa canina",
    "Rosa chinensis viridiflora",
    "Rosa x hybrida astronomia",
    "Rosmarinus officinalis",
    "Rostrinucula dependens",
    "Rubus",
    "Rubus fruticosus",
    "Rubus idaeus",
    "Rubus thibetanus",
    "Rudbeckia",
    "Rumex acetosa",
    "Rumex patientia",
    "Sagina subulata",
    "Saintpaulia",
    "Salix",
    "Salix integra 'hakuro nishiki'",
    "Salvia",
    "Salvia officinalis",
    "Sambucus",
    "Sambucus nigra",
    "Sanguinaria canadensis",
    "Sanguisorba",
    "Saponaria officinalis",
    "Sarracenia",
    "Sassafras albidum",
    "Satureja",
    "Satureja douglasii",
    "Saxifraga",
    "Scadoxus multiflorus",
    "Schisandra grandiflora",
    "Schizachyrium scoparium",
    "Schizophragma hydrangeoides",
    "Schizostylis coccinea",
    "Schlumbergera",
    "Sciadopitys verticillata",
    "Scilla peruviana",
    "Scleranthus uniflorus",
    "Sechium",
    "Sedum",
    "Sedum morganianum",
    "Semiarundinaria",
    "Sempervivum",
    "Senecio cineraria",
    "Senecio monroi",
    "Senna corymbosa",
    "Sequoia",
    "Silene",
    "Sinapis alba",
    "Sinojackia xylocarpa",
    "Sisyrinchium",
    "Sisyrinchium angustifolium",
    "Solanum aethiopicum",
    "Solanum crispum",
    "Solanum jasminoïdes",
    "Solanum muricatum",
    "Solanum rantonnetii",
    "Soleirolia",
    "Solenostemon",
    "Solidago",
    "Sollya heterophylla",
    "Sophora japonica",
    "Sophora microphylla",
    "Sorbaria sorbifolia",
    "Sorbus aucuparia",
    "Sorbus domestica",
    "Sorbus torminalis",
    "Sparaxis",
    "Spartium junceum",
    "Spilanthes oleraceae",
    "Spiraea",
    "Spiraea x vanhouttei",
    "Stachys affinis",
    "Stachys byzantina",
    "Stachys lanata",
    "Stachyurus chinensis",
    "Stapelia variegata",
    "Staphylea pinnata",
    "Statice latifolium",
    "Statice sinuata",
    "Stauntonia",
    "Stephanandra incisa 'crispa'",
    "Sternbergia",
    "Stewartia pseudocamellia",
    "Stipa tenuissima",
    "Stratiotes aloides",
    "Strelitzia reginae",
    "Streptocarpus",
    "Strobilanthes",
    "Styrax",
    "Syngonium podophyllum",
    "Syringa",
    "Tagetes patula",
    "Tamarix",
    "Tanacetum balsamita",
    "Tanacetum coccineum",
    "Tasmannia lanceolata",
    "Taxus",
    "Telopea",
    "Tetradenia riparia",
    "Tetradium daniellii var. hupehensis",
    "Teucrium fruticans",
    "Thalictrum",
    "Thamnochortus cinereus",
    "Thevetia peruviana",
    "Thuya",
    "Thymus",
    "Thymus x citriodorus",
    "Tiarella",
    "Tigridia",
    "Tilia",
    "Tillia",
    "Titanotrichum oldhamii",
    "Tolmiea",
    "Toona sinensis",
    "Torenia",
    "Trachelium",
    "Trachelospermum jasminoides",
    "Trachycarpus",
    "Trachystemon orientalis",
    "Tricyrtis",
    "Trillium",
    "Triteleia",
    "Trochodendron aralioides",
    "Tropaeolum",
    "Tulbaghia violacea",
    "Tulipa",
    "Tweedia caerulea",
    "Typha",
    "Ulex europaeus",
    "Ulmus",
    "Uncinia rubra",
    "Urginea maritima",
    "Vaccinium",
    "Vaccinium macrocarpon",
    "Valerianella",
    "Veltheimia",
    "Verbascum",
    "Verbena bonariensis",
    "Verbena officinalis",
    "Verbena rigida",
    "Verbena x hybrida",
    "Viburnum",
    "Viburnum",
    "Viburnum lantana",
    "Viburnum opulus",
    "Viburnum plicatum",
    "Viburnum rhytidophyllum",
    "Viburnum tinus",
    "Viburnum x burkwoodii",
    "Vigna unguiculata",
    "Vinca",
    "Viola",
    "Viola cornuta",
    "Viola odorata",
    "Vitex agnus-castus",
    "Vitis coignetiae",
    "Vitis vinifera",
    "Waldsteinia ternata",
    "Wasabia japonica",
    "Washingtonia filifera",
    "Weigela",
    "Westringia longifolia",
    "Wisteria",
    "Wisteria floribunda",
    "Yucca",
    "Yucca elephantipes",
    "Zamioculcas",
    "Zantedeschia",
    "Zanthoxylum",
    "Zingiber mioga",
    "Zinnia",
    "Ziziphus jujuba",
    "Zoysia tenuifolia",
];
