// This table store all the countries
export const countriesToFetch: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Ivory Coast",
  "Cape Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Republic of the Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "DR Congo",
  "Denmark",
  "Djibouti",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Vatican City",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// There is currently 467 animal species in this array
export const animalsLatinNames: string[] = [
  "Canis lupus familiaris",
  "Felis catus",
  "Equus ferus caballus",
  "Panthera leo",
  "Panthera tigris",
  "Ursus arctos",
  "Giraffa camelopardalis",
  "Elephas maximus",
  "Serpentes",
  "Crocodylidae",
  "Delphinus delphis",
  "Aptenodytes forsteri",
  "Macropus",
  "Phascolarctos cinereus",
  "Simia",
  "Vulpes vulpes",
  "Canis lupus",
  "Aves",
  "Pisces",
  "Selachimorpha",
  "Gorilla gorilla",
  "Hippopotamus amphibius",
  "Equus zebra",
  "Rhinoceros unicornis",
  "Struthio camelus",
  "Aquila chrysaetos",
  "Gallus gallus",
  "Anas platyrhynchos",
  "Pavo cristatus",
  "Bubo bubo",
  "Psittaciformes",
  "Erinaceus europaeus",
  "Panthera pardus",
  "Acinonyx jubatus",
  "Gazella",
  "Bubalus bubalis",
  "Camelus dromedarius",
  "Canis aureus",
  "Naja",
  "Formicidae",
  "Rana",
  "Iguana",
  "Lutra",
  "Ovis aries",
  "Orcinus orca",
  "Rattus",
  "Talpa",
  "Bos taurus",
  "Bos grunniens",
  "Balaenoptera",
  "Astacidea",
  "Mustela putorius furo",
  "Hylobates",
  "Cricetinae",
  "Panthera onca",
  "Oryctolagus cuniculus",
  "Marmota",
  "Monodon monoceros",
  "Otariidae",
  "Ailuropoda melanoleuca",
  "Setonix brachyurus",
  "Procyon lotor",
  "Salamandra",
  "Myrmecophaga tridactyla",
  "Vultur",
  "Macropodidae",
  "Xerus",
  "Abominable snowman",
  "Ictonyx striatus",
  "Elephantidae",
  "Tapirus terrestris",
  "Lemur catta",
  "Dromaius novaehollandiae",
  "Cygnus olor",
  "Camelidae",
  "Chinchilla lanigera",
  "Alces alces",
  "Cervus elaphus",
  "Capra aegagrus hircus",
  "Thylacinus cynocephalus",
  "Chelonia mydas",
  "Spheniscus demersus",
  "Pteropus",
  "Colobus guereza",
  "Puma concolor",
  "Didelphis virginiana",
  "Tursiops truncatus",
  "Castor fiber",
  "Equus quagga",
  "Dasyurus",
  "Sus scrofa",
  "Hyaenidae",
  "Lepus",
  "Phocoena phocoena",
  "Sirenia",
  "Gekkota",
  "Oncorhynchus mykiss",
  "Cyprinidae",
  "Eschrichtius robustus",
  "Loris",
  "Carcharhinus",
  "Scombridae",
  "Corvus corax",
  "Squalidae",
  "Strigiformes",
  "Bos mutus",
  "Equus grevyi",
  "Columbidae",
  "Psittacidae",
  "Psittacula krameri",
  "Eulemur",
  "Phalangeridae",
  "Notoryctemorphia",
  "Anseriformes",
  "Eubalaena",
  "Anser anser",
  "Vespertilionidae",
  "Cervidae",
  "Chiroptera",
  "Eutheria",
  "Rhinocerotidae",
  "Arctocephalus",
  "Bos primigenius",
  "Megalonychidae",
  "Cypriniformes",
  "Corvus brachyrhynchos",
  "Cygnus atratus",
  "Felis silvestris catus",
  "Odocoileus virginianus",
  "Gorilla beringei",
  "Meles meles",
  "Cervus nippon",
  "Didelphis marsupialis",
  "Balaenoptera musculus",
  "Caiman crocodilus",
  "Stegostoma fasciatum",
  "Cygnus buccinator",
  "Equus africanus asinus",
  "Equus zebra zebra",
  "Stegostoma tigrinum",
  "Melopsittacus undulatus",
  "Cygnus cygnus",
  "Phocoena sinus",
  "Melursus ursinus",
  "Caretta caretta",
  "Ciconiiformes",
  "Viverridae",
  "Pogona vitticeps",
  "Ctenocephalides felis",
  "Bison bison",
  "Tetraodontidae",
  "Pagophilus groenlandicus",
  "Lagenorhynchus acutus",
  "Vombatus ursinus",
  "Sciuridae",
  "Elasmobranchii",
  "Alcelaphus buselaphus",
  "Ursidae",
  "Nyctereutes procyonoides",
  "Lama glama",
  "Orycteropus afer",
  "Pteropus vampyrus",
  "Mustela erminea",
  "Pogona barbata",
  "Antilocapra americana",
  "Lagenorhynchus obliquidens",
  "Dugong dugon",
  "Equus hemionus",
  "Dasypus novemcinctus",
  "Oryx leucoryx",
  "Lagenorhynchus albirostris",
  "Chlamydosaurus kingii",
  "Callithrix jacchus",
  "Chelydra serpentina",
  "Cervus canadensis",
  "Trichechus manatus",
  "Chinchilla chinchilla",
  "Gazella dama",
  "Dasyprocta",
  "Mustela nivalis",
  "Camelus ferus",
  "Coelacanth",
  "Delphinapterus leucas",
  "Echidna",
  "Melursus ursinus ursinus",
  "Equus asinus",
  "Sphaeramia nematoptera",
  "Aegypius monachus",
  "Lemur",
  "Pongo",
  "Equus przewalskii",
  "Lemur fulvus",
  "Phoca",
  "Equus burchelli",
  "Tarsius",
  "Antilopinae",
  "Geochelone",
  "Phascolarctos",
  "Gallus",
  "Felis",
  "Equus quagga quagga",
  "Equus africanus",
  "Cervus",
  "Tachyglossidae",
  "Mellivora capensis",
  "Mustela",
  "Didelphimorphia",
  "Equus ferus",
  "Odobenus rosmarus",
  "Hylobates lar",
  "Erinaceinae",
  "Ceratotherium simum",
  "Galeopterus variegatus",
  "Leporidae",
  "Marmota monax",
  "Dasypus",
  "Vulpes",
  "Hippopotamus",
  "Canidae",
  "Perissodactyla",
  "Tragulidae",
  "Hominidae",
  "Lepidosauria",
  "Callorhinus ursinus",
  "Phasianidae",
  "Psittaculidae",
  "Lorisidae",
  "Macropodinae",
  "Notoryctidae",
  "Vespertilioninae",
  "Suidae",
  "Felidae",
  "Didelphidae",
  "Delphinidae",
  "Castoridae",
  "Anatidae",
  "Balaenopteridae",
  "Mammalia",
  "Bovidae",
  "Phoxinus phoxinus",
  "Ruminantia",
  "Dinosauria",
  "Falconiformes",
  "Mustelidae",
  "Panthera",
  "Dasypodidae",
  "Rodentia",
  "Artiodactyla",
  "Pinnipedia",
  "Chinchillidae",
  "Soricidae",
  "Pelecaniformes",
  "Cetacea",
  "Lar gibbon",
  "Erinaceidae",
  "Pteropodidae",
  "Agamidae",
  "Antilocapridae",
  "Dugongidae",
  "Equus",
  "Oryx",
  "Callitrichidae",
  "Chelydridae",
  "Trichechus",
  "Gazella dama mhorr",
  "Dasyproctidae",
  "Coelacanthiformes",
  "Delphinapterus",
  "Tachyglossus",
  "Pterophyllum scalare",
  "Orcinus",
  "Lemuridae",
  "Pongo pygmaeus",
  "Phocidae",
  "Tarsius tarsier",
  "Geochelone nigra",
  "Gallus gallus domesticus",
  "Felis silvestris",
  "Rhincodontidae",
  "Ceratotheriidae",
  "Cheloniidae",
  "Spheniscidae",
  "Cercopithecidae",
  "Naja naja",
  "Rana temporaria",
  "Iguana iguana",
  "Lutra lutra",
  "Rattus norvegicus",
  "Talpa europaea",
  "Balaenoptera physalus",
  "Salamandra salamandra",
  "Vultur gryphus",
  "Yeti",
  "Pristidae",
  "Prionailurus bengalensis",
  "Odocoileus hemionus",
  "Cygnus columbianus",
  "Equus ferus przewalskii",
  "Cathartidae",
  "Ammodytes tobianus",
  "Phoca vitulina",
  "Dasyatis",
  "Castor canadensis",
  "Scolopacidae",
  "Pteronura brasiliensis",
  "Lepus europaeus",
  "Heterocephalus glaber",
  "Odocoileus",
  "Salvelinus fontinalis",
  "Equus caballus",
  "Ovis orientalis musimon",
  "Oryx gazella",
  "Callithrix penicillata",
  "Colobinae",
  "Eurasian magpie",
  "Equus burchelli boehmi",
  "Aegypius tracheliotus",
  "Mustela nivalis vulgaris",
  "Ciconia ciconia",
  "Lepus timidus",
  "Chelonia",
  "Pongo abelii",
  "Procyon",
  "Frog",
  "Iguanidae",
  "Ardeidae",
  "Cervus unicolor",
  "Mephitis mephitis",
  "Equus kiang",
  "Perameles nasuta",
  "Fulmarus glacialis",
  "Gulo gulo",
  "Cervus canadensis nelsoni",
  "Nasalis larvatus",
  "Mustelinae",
  "Mammuthus",
  "Echeneis naucrates",
  "Alouatta",
  "Mustela lutreola",
  "Ailurus",
  "Lama",
  "Phasianus colchicus",
  "Gorilla gorilla gorilla",
  "Petauridae",
  "Equus grevyi grevyi",
  "Columba livia",
  "Cygnus melancoryphus",
  "Carcharodon carcharias",
  "Papio hamadryas",
  "Papio cynocephalus",
  "Bos grunniens grunniens",
  "Sus scrofa domesticus",
  "Papio",
  "Vespa crabro",
  "Bos indicus",
  "Vespertilio murinus",
  "Gorilla gorilla diehli",
  "Lissotriton vulgaris",
  "Mustela vison",
  "Thylacine",
  "Camelus",
  "Tursiops",
  "Melursus",
  "Equus kiang polyodon",
  "Chelonia mydas mydas",
  "Panthera pardus orientalis",
  "Dugong",
  "Myrmecophagidae",
  "Mustela nivalis nivalis",
  "Ursus americanus",
  "Zalophus californianus",
  "Elephant seal",
  "Procyonidae",
  "Urocyon cinereoargenteus",
  "Ailuropoda",
  "Mustela putorius",
  "Macropus rufus",
  "Vulpes velox",
  "Alopex lagopus",
  "Odobenidae",
  "Phoca largha",
  "Chlamydosaurus",
  "Balaenoptera acutorostrata",
  "Thalasseus maximus",
  "Nasua nasua",
  "Pteropus giganteus",
  "Tursiops truncatus truncatus",
  "Alopex",
  "Geochelone gigantea",
  "Equus africanus somaliensis",
  "Castor canadensis canadensis",
  "Naja haje",
  "Acrocephalus arundinaceus",
  "Panthera tigris sumatrae",
  "Naja kaouthia",
  "Mustela nigripes",
  "Eumetopias jubatus",
  "Macropus fuliginosus",
  "Equus asinus asinus",
  "Mustela putorius putorius",
  "Mustela altaica",
  "Mustela erminea aestiva",
  "Mustela erminea hibernica",
  "Mustela erminea arctica",
  "Mustela frenata",
  "Phascolarctos cinereus adustus",
  "Sirenidae",
  "Odobenus",
  "Eudyptes chrysolophus",
  "Carcharhinus leucas",
  "Phalacrocorax carbo",
  "Alcelaphus",
  "Bison bison bison",
  "Ammodytes",
  "Vulpes ferrilata",
  "Phocoenidae",
  "Equus kiang kiang",
  "Ursus maritimus",
  "Alces",
  "Callithrix",
  "Ara ararauna",
  "Chelydra",
  "Equus grevyi pygmaeus",
  "Echeneis",
  "Gulo",
  "Gorilla",
  "Dromaius",
  "Cygnus",
  "Phascolarctos cinereus cinereus",
  "Hyaena",
  "Globicephala melas",
  "Eulemur fulvus",
  "Dendrolagus",
  "Haliaeetus leucocephalus",
  "Ara macao",
  "Hippopotamidae",
  "Equus africanus africanus",
  "Castor",
  "Panthera leo persica",
  "Equus burchellii boehmi",
  "Acinonyx jubatus jubatus",
  "Scomber scombrus",
  "Haliaeetus albicilla",
  "Hippocampus hippocampus",
  "Mustela erminea nivalis",
  "Mustela nigripes nigripes",
  "Puma",
  "Chlamyphoridae",
  "Ursus",
  "Pogona",
  "Acinonyx",
  "Sphyrnidae",
  "Phocoena",
  "Phasianus",
  "Thalasseus",
  "Eudyptes",
  "Lagenorhynchus",
  "Lissotriton",
  "Globicephala",
  "Phalacrocorax",
  "Equus hemionus hemionus",
  "Gorilla beringei beringei",
  "Odobenus rosmarus rosmarus",
  "Hyaena hyaena",
  "Ciconiidae",
  "Papio ursinus",
  "Macropus robustus",
  "Thalasseus sandvicensis",
  "Papio papio",
  "Papio anubis",
  "Ailurus fulgens",
  "Ammodytes marinus",
  "Canis lupus dingo",
  "Lepus americanus",
  "Camelus bactrianus",
  "Hippocampus",
  "Mustela ermine",
  "Acanthosoma haemorrhoidale",
  "Acromyrmex octospinosus",
  "Actina chalybea",
  "Adalia decempunctata",
  "Adelphocoris lineolatus",
  "Aelia acuminata",
  "Agapanthia villosoviridescens",
  "Agelastica alni",
  "Agriotes pilosellus",
  "Aleocharinae",
  "Allantus cinctus",
  "Allygus modestus",
  "Ammophila sabulosa",
  "Ampedus cinnaberinus",
  "Ancistrocerus sp.",
  "Andrena cineraria",
  "Andrena fulva",
  "Anoplotrupes stercorosus",
  "Anthophora plumipes",
  "Aphis sambuci",
  "Aphrophora alni",
  "Apiomerus sp.",
  "Apis mellifera",
  "Arcyptera fusca",
  "Arge pagana",
  "Arma custos",
  "Asiraca clavicornis",
  "Bibio marci",
  "Bombus (Terrestribombus) sp.",
  "Bombus pascuorum",
  "Bombylius major",
  "Brachyleptura fulva",
  "Caliprobola speciosa",
  "Calliptamus wattenwylianus",
  "Calvia quattuordecimguttata",
  "Camponotus vagus",
  "Campopleginae sp.",
  "Campyloneura virgula",
  "Cantharis livida",
  "Cantharis rustica",
  "Capnodis tenebrionis",
  "Capsodes gothicus",
  "Carabus problematicus",
  "Carpocoris purpureipennis",
  "Ceraleptus gracilicornis",
  "Cerambyx scopolii",
  "Cercopis vulnerata",
  "Cetonia aurata",
  "Cheilosia albitarsis",
  "Cheilosia illustrata",
  "Chironomus plumosus",
  "Chloromyia formosa",
  "Chlorophorus glabromaculatus",
  "Chorthippus brunneus-biguttulus-mollis",
  "Chrysis sp.",
  "Chrysochraon dispar",
  "Chrysogaster solstitialis",
  "Chrysopa perla",
  "Chrysoperla carnea",
  "Chrysotoxum festivum",
  "Chyromya sp.",
  "Cicadella viridis",
  "Cicadellidae sp.",
  "Cicindela campestris",
  "Cimbex femoratus",
  "Cionus scrophulariae",
  "Cixius nervosus",
  "Cleonis pigra",
  "Clerus mutillarius",
  "Cloeon sp.",
  "Clogmia albipunctata",
  "Clytra laeviuscula",
  "Clytus arietis",
  "Coccinella septempunctata",
  "Conocephalus fuscus",
  "Conomelus anceps",
  "Coreus marginatus",
  "Corizus hyoscyami",
  "Cornops aquaticum",
  "Cortodera humeralis",
  "Criorhina ranunculi",
  "Cteniopus sulphureus",
  "Ctenophora festiva",
  "Culex pipiens",
  "Culiseta annulata",
  "Curculio nucum",
  "Cylindromyia bicolor",
  "Dasypoda hirtipes",
  "Dasytes caeruleus",
  "Delta unguiculatum",
  "Dendroxena quadrimaculata",
  "Deraeocoris ruber",
  "Diaperis boleti",
  "Dinera ferina",
  "Dixidae sp.",
  "Dolichomitus imperator",
  "Dolycoris baccarum",
  "Dorcus parallelipipedus",
  "Dorytomus longimanus",
  "Drilus flavescens",
  "Ectobius lapponicus",
  "Ectobius sylvestris",
  "Ectobius vinzi",
  "Elasmucha grisea",
  "Eliozeta pellucens",
  "Empis tessellata",
  "Eneoptera sp.",
  "Ephemera glaucops",
  "Epiphragma ocellare",
  "Episyrphus balteatus",
  "Eristalis abusiva",
  "Eristalis arbustorum",
  "Eristalis intricaria",
  "Eristalis pertinax",
  "Eristalis tenax",
  "Erotylus giganteus",
  "Euceraphis sp.",
  "Euchorthippus declivus",
  "Euleia heraclei",
  "Eupeodes corollae",
  "Eurydema oleracea",
  "Eurydema ornata",
  "Eurygaster testudinaria",
  "Euthystira brachyptera",
  "Evacanthus interruptus",
  "Eysarcoris venustissimus",
  "Forficula auricularia",
  "Gasteruption sp.",
  "Geomyza tripunctata",
  "Gomphocerippus rufus",
  "Graphomya maculata",
  "Graphosoma italicum",
  "Gymnosoma rotundatum",
  "Halictus scabiosae",
  "Harmonia axyridis",
  "Harmonia quadripunctata",
  "Harpocera thoracica",
  "Hedychrum nobile",
  "Hedychrum rutilans",
  "Helophilus pendulus",
  "Helophilus trivittatus",
  "Hemicrepidius hirtus",
  "Hemipenthes morio",
  "Himacerus apterus",
  "Himacerus mirmicoides",
  "Hispa atra",
  "Ichneumon extensorius",
  "Idiocerus lituratus",
  "Issus coleoptratus",
  "Kleidocerys resedae",
  "Lampyris noctiluca",
  "Larinus turbinatus",
  "Lasius emarginatus",
  "Ledra aurita",
  "Leiopus femoratus",
  "Leptinotarsa decemlineata",
  "Leptoglossus occidentalis",
  "Leptophyes punctatissima",
  "Licinus hoffmannseggi",
  "Limnia unguicornis",
  "Liophloeus tessulatus",
  "Lissonota sp.",
  "Lixus iridis",
  "Loensia fasciata",
  "Lygaeus equestris",
  "Lygaeus simulans",
  "Lygus pratensis",
  "Machilidae sp.",
  "Macrophya duodecimpunctata",
  "Macrosiphum rosae",
  "Malachius bipustulatus",
  "Manicocoris rufipes",
  "Mantidae sp.",
  "Mantis religiosa",
  "Meconema thalassinum",
  "Mecostethus parapleurus",
  "Medetera sp.",
  "Meiosimyza rorida",
  "Melanocoryphus albomaculatus",
  "Melasoma populi",
  "Meliscaeva auricollis",
  "Melolontha melolontha",
  "Merodon equestris",
  "Mesosa nebulosa",
  "Micromus angulatus",
  "Miramella alpina",
  "Mocydia crocea",
  "Mononychus punctumalbum",
  "Mordellidae sp.",
  "Myathropa florea",
  "Nacerdes carniolica",
  "Nasutitermes sp.",
  "Nematus poecilonotus",
  "Nematus ribesii",
  "Nemobius sylvestris",
  "Nephrotoma appendiculata",
  "Nephrotoma flavescens",
  "Nephrotoma quadrifaria",
  "Nezara viridula",
  "Nogodinidae",
  "Nomada lathburiana",
  "Notostira elongata",
  "Odynerus sp.",
  "Oecanthus pellucens",
  "Oedemera nobilis",
  "Oedemera podagrariae",
  "Oedipoda caerulescens",
  "Oiceoptoma thoracicum",
  "Omocestus rufipes",
  "Omocestus viridulus",
  "Ophion obscuratus",
  "Oreina menthastri",
  "Osmia cornuta",
  "Otiorhynchus sp.",
  "Ovalisia festiva",
  "Oxyna flavipennis",
  "Oxythyrea funesta",
  "Pachyrhinus lethierryi",
  "Pachytodes cerambyciformis",
  "Palomena prasina",
  "Panorpa communis",
  "Panorpa germanica",
  "Pantilius tunicatus",
  "Pentatoma rufipes",
  "Peribalus strictus",
  "Periclista sp",
  "Phaeostigma notata",
  "Phaneroptera falcata",
  "Phaneroptera nana",
  "Phaonia pallida",
  "Phaonia subventa",
  "Pherbellia cinerella",
  "Philaenus spumarius",
  "Pholidoptera griseoaptera",
  "Phyllobius betulinus",
  "Phyllobius glaucus",
  "Phyllobius pomaceus",
  "Phyllobius pyri",
  "Physiphora alceae",
  "Plagionotus detritus",
  "Platystoma seminationis",
  "Poecilopompilus sp.",
  "Polistes bischoffi",
  "Polistes dominula",
  "Polistes nimpha",
  "Polydrusus cervinus",
  "Polydrusus formosus",
  "Polydrusus impressifrons",
  "Prionus coriarius",
  "Propylea quatuordecimpunctata",
  "Pseudochorthippus parallelus",
  "Pseudovadonia livida",
  "Psychoda sp.",
  "Psychoda surcoufi",
  "Psyllobora vigintiduopunctata",
  "Ptychoptera albimana",
  "Pyrochroa coccinea",
  "Pyrochroa serraticornis",
  "Pyrrhocoris apterus",
  "Rainiera calceata",
  "Rhadinoceraea micans",
  "Rhagio scolopaceus",
  "Rhagio vitripennis",
  "Rhagonycha fulva",
  "Rhaphigaster nebulosa",
  "Rhizotrogus aestivus",
  "Rhopalus subrufus",
  "Rhyparochromus vulgaris",
  "Ruspolia nitidula",
  "Rutpela maculata",
  "Sapromyza sexpunctata",
  "Sarcophaga carnaria",
  "Scaeva pyrastri",
  "Scathophaga stercoraria",
  "Schistocerca americana",
  "Sciara sp.",
  "Scymninae sp.",
  "Sialis lutaria",
  "Sicus ferrugineus",
  "Sphaerophoria scripta",
  "Sphecodes albilabris",
  "Spilostethus pandurus",
  "Stenidiocerus poecilus",
  "Stenobothrus lineatus",
  "Stenodema laevigata",
  "Stenopterus rufus",
  "Stenurella melanura",
  "Stictocephala bisonia",
  "Suillia variegata",
  "Sylvicola fenestralis",
  "Sylvicola fuscatus",
  "Synophropsis lauri",
  "Syrphus vitripennis",
  "Tachina fera",
  "Tachina grossa",
  "Tachina magnicornis",
  "Taeniotes subocellatus",
  "Tenthredo marginella-thompsoni",
  "Tettigonia viridissima",
  "Thelaira solivaga",
  "Timarcha tenebricosa",
  "Tipula (Lunatipula) fascipennis",
  "Tipula (Lunatipula) sp",
  "Tipula (Savtshenkia) pagana",
  "Tipula (Yamatotipula) gr lateralis",
  "Tipula lunata",
  "Tipula oleracea",
  "Tipula paludosa",
  "Tipula rufina",
  "Tipula varipennis",
  "Tipula vernalis",
  "Trichius fasciatus",
  "Trichius zonatus",
  "Trichodes alvearius",
  "Trichodes apiarius",
  "Tritomegas bicolor",
  "Tropidacris collaris",
  "Tropidothorax leucopterus",
  "Trypetoptera punctulata",
  "Uroleucon sp.",
  "Valgus hemipterus",
  "Vespa crabro",
  "Vespa velutina",
  "Vespula germanica",
  "Vespula vulgaris",
  "Volucella bombylans",
  "Volucella pellucens",
  "Volucella zonaria",
  "Wesmaelius sp.",
  "Xylocopa violacea",
  "Xylotrechus antilope",
  "Zophomyia temula",
];

// There is currently 906 plant species in this array
export const plantsLatinNames: string[] = [
  "Abelia",
  "Abelmoschus esculentus",
  "Abies",
  "Abutilon",
  "Acacia dealbata",
  "Acacia deanei",
  "Acanthus mollis",
  "Acanthus spinosus",
  "Acer",
  "Acer palmatum",
  "Acer pseudoplatanus",
  "Achillea",
  "Achillea filipendulina",
  "Acidanthera murielae",
  "Acmella oleracea",
  "Aconitum",
  "Acorus gramineus",
  "Acroclinium",
  "Actaea",
  "Actinidia",
  "Actinidia arguta",
  "Adansonia",
  "Adenium obesum",
  "Adiantum",
  "Adonis aestivalis",
  "Aechmea",
  "Aeonium",
  "Aesculus",
  "Aesculus parviflora",
  "Agapanthus",
  "Agastache",
  "Agathea caelestis",
  "Agave",
  "Aglaonema",
  "Ajania pacifica",
  "Ajuga",
  "Akebia",
  "Albizia",
  "Alcea",
  "Alchemilla",
  "Allium",
  "Allium cepa",
  "Allium cepa var. proliferum",
  "Allium porrum",
  "Allium sativum",
  "Allium schoenoprasum",
  "Allium ursinum",
  "Alnus",
  "Aloe",
  "Aloysia triphylla",
  "Alpinia purpurata",
  "Alstroemeria",
  "Althea officinalis",
  "Alyssum",
  "Amaranthus",
  "Amelanchier",
  "Amicia zygomeris",
  "Ammi",
  "Ampelodesmos mauritanicus",
  "Amsonia",
  "Anacyclus pyrethrum var. depressus",
  "Anagallis monelli",
  "Ananas",
  "Anaphalis margaritacea",
  "Anchusa",
  "Andromeda polifolia",
  "Anemone blanda",
  "Anemone coronaria",
  "Anemone hupehensis",
  "Anethum",
  "Anigozanthos rufus",
  "Anisodontea capensis",
  "Anthemis",
  "Anthriscus",
  "Anthriscus sylvestris",
  "Anthurium",
  "Antirrhinum majus",
  "Apios americana",
  "Apium graveolens",
  "Aptenia cordifolia",
  "Aquilegia",
  "Arabis",
  "Araucaria araucana",
  "Araucaria heterophylla",
  "Araujia sericifera",
  "Arbutus",
  "Arisaema",
  "Aristolochia macrophylla",
  "Arnica montana",
  "Artemisia",
  "Artemisia abrotanum",
  "Artemisia dracunculus",
  "Arthropodium cirrhatum",
  "Aruncus",
  "Arundo donax",
  "Asarum",
  "Asclepias tuberosa",
  "Ascocenda",
  "Asimina triloba",
  "Aspidistra",
  "Asplenium scolopendrium",
  "Astelia",
  "Aster",
  "Astilbe",
  "Astragalus membranaceus",
  "Astrancia",
  "Atriplex",
  "Atriplex halimus",
  "Aubrieta",
  "Aucuba",
  "Azalea japonica",
  "Azara microphylla",
  "Azorella trifurcata",
  "Ballota pseudodictamnus",
  "Balsamita major",
  "Bambusa",
  "Baptisia australis",
  "Begonia maculata",
  "Begonia rex-cultorum",
  "Begonia semperflorens",
  "Bellis",
  "Beloperone guttata",
  "Berberidopsis corallina",
  "Berberis",
  "Bergenia",
  "Beta vulgaris",
  "Betula",
  "Bignonia capreolata",
  "Billardiera heterophylla",
  "Blechnum spicant",
  "Boccania cordata",
  "Boehmeria",
  "Boltonia",
  "Borago",
  "Boronia crenulata",
  "Boronia heterophylla",
  "Bougainvillea",
  "Brachyglottis monroi",
  "Brachyscome",
  "Brassada",
  "Brassia",
  "Brassica oleracea",
  "Brassica oleracea botrytis var. cymosa",
  "Brassica rapa japonica",
  "Brighamia insignis",
  "Briza",
  "Briza maxima",
  "Briza media",
  "Brunnera",
  "Buddleja",
  "Bulbine frutescens",
  "Buxus",
  "Caesalpinia gilliesii",
  "Caladium",
  "Calamagrostis",
  "Calceolaria",
  "Calibrachoa",
  "Callistemon",
  "Callistephus chinensis",
  "Calluna",
  "Calocephalus brownii",
  "Calycanthus floridus",
  "Camassia",
  "Camellia",
  "Campanula",
  "Campanula rapunculus",
  "Campsis",
  "Canna",
  "Capsicum",
  "Cardamine hirsuta",
  "Carex",
  "Carica papaya",
  "Carissa macrocarpa",
  "Carpinus",
  "Carpobrotus",
  "Carum carvi",
  "Carya illinoinensis",
  "Cassia corymbosa",
  "Castanea",
  "Catalpa",
  "Catharanthus roseus",
  "Ceanothus",
  "Cedrela sinensis",
  "Cedrus",
  "Ceiba speciosa",
  "Celosia argentea",
  "Centaurea",
  "Centranthus ruber",
  "Cerastium tomentosum",
  "Cercidiphyllum japonicum",
  "Cereus hildmannianus",
  "Cerinthe major purpurascens",
  "Ceropegia woodii",
  "Chaenomeles",
  "Chaerophyllum bulbosum",
  "Chamaedorea",
  "Chamaemelum nobile",
  "Chamaerops humilis",
  "Chasmanthe floribunda",
  "Cheiranthus cheiri",
  "Chelone lyonii",
  "Chelone obliqua",
  "Chenopodium bonus-henricus",
  "Chionodoxa",
  "Chitalpa tashkentensis",
  "Choisya ternata",
  "Chorisia speciosa",
  "Choysia ternata",
  "Chrysanthemum",
  "Chrysanthemum coccineum",
  "Cicer arietinum",
  "Cichorium",
  "Cichorium endivia var. latifolium",
  "Cissus rhombifolia",
  "Cistus",
  "Citrullus lanatus",
  "Citrus aurantiifolia",
  "Citrus hystrix",
  "Citrus juno",
  "Citrus latifolia",
  "Citrus limon",
  "Citrus sinensis",
  "Citrus x meyeri",
  "Citrus x paradisi",
  "Clatteya",
  "Claytonia perfoliata",
  "Clematis",
  "Clematis armandii",
  "Clematis montana",
  "Clematis texensis",
  "Cleome",
  "Clerodendron",
  "Clethra alnifolia",
  "Clethra barbinervis",
  "Clianthus puniceus",
  "Clinopodium douglasii",
  "Clivia",
  "Clusia",
  "Cobaea scandens",
  "Cocos nucifera",
  "Codiaeum",
  "Coffea arabica",
  "Colchicum",
  "Colocasia esculenta",
  "Colutea arborescens",
  "Commelina tuberosa",
  "Convollaria majalis",
  "Convolvulus tricolor",
  "Coreopsis",
  "Coriandrum sativum",
  "Cornus",
  "Cornus florida",
  "Corokia cotoneaster",
  "Coronilla",
  "Corydalis",
  "Corylopsis",
  "Corylus avellana",
  "Cosmos",
  "Cotoneaster",
  "Crambe maritima",
  "Craspedia",
  "Crassula",
  "Crataegus",
  "Crinodendron hookerianum",
  "Crinum",
  "Crocosmia",
  "Crocus",
  "Crocus ancyrensis",
  "Ctenanthe setosa",
  "Cucumis anguria",
  "Cucumis melo",
  "Cucumis sativus",
  "Cucurbita maxima",
  "Cupressocyparis leylandii",
  "Cupressus",
  "Cupressus macrocarpa",
  "Curcurbita",
  "Curcurbita pepo",
  "Cycas",
  "Cyclamen coum",
  "Cyclamen hederifolium",
  "Cyclamen purpurascens",
  "Cydonia",
  "Cymbopogon citratus",
  "Cynara",
  "Cyperus",
  "Cytisus scoparius",
  "Daboecia",
  "Dahlia",
  "Dahlia imperialis",
  "Daphne mezereum",
  "Darwinia oxylepis",
  "Dasylirion",
  "Daucus carota",
  "Davallia fejeensis",
  "Davidia involucrata",
  "Delphinium",
  "Deschampsia",
  "Deutzia",
  "Dianthus",
  "Dianthus barbatus",
  "Dianthus carthusianorum",
  "Diascia",
  "Dicentra eximia",
  "Dicentra spectabilis",
  "Dichelostemma multiflorum",
  "Dichondra repens",
  "Dichromena colorata",
  "Dierama pulcherrimum",
  "Digitalis",
  "Disporopsis pernyi",
  "Disporum",
  "Dodonea viscosa 'purpurea'",
  "Dolichos sesquipedalis",
  "Doronicum",
  "Dorycnium hirsutum",
  "Dracaena sanderiana",
  "Dregea sinensis",
  "Drimys aromatica",
  "Dypsis decaryi",
  "Echeveria",
  "Echium",
  "Edgeworthia chrysantha",
  "Elaeagnus angustifolia",
  "Eleagnus multiflora",
  "Elegia capensis",
  "Elsholtzia stauntonii",
  "Embothrium coccineum",
  "Enkianthus campanulatus",
  "Ensete ventricosum var. maurelii",
  "Epimedium",
  "Epiphyllum",
  "Equisetum fluviatile",
  "Equisetum hyemale",
  "Eragrostis",
  "Eranthis hyemalis",
  "Erica",
  "Erica arborea",
  "Eriobotrya japonica",
  "Eriostemon myrioporoïdes",
  "Erodium",
  "Eryngium",
  "Erysimum",
  "Erythrina crista-galli",
  "Erythronium",
  "Eschscholtzia californica",
  "Eucalyptus",
  "Eucomis",
  "Eucryphia",
  "Euodia daniellii var. hupehensis",
  "Euonymus",
  "Euonymus japonicus",
  "Eupatorium",
  "Eupatorium rugosum 'chocolate'",
  "Euphorbia",
  "Euphorbia griffithii",
  "Euphorbia pulcherrima",
  "Eutrema japonicum",
  "Fagopyrum cymosum",
  "Fagopyrum dibotrys",
  "Fagopyrum esculentum",
  "Fagus",
  "Fallopia baldschuanica",
  "Farfugium japonicum",
  "Fatsia japonica",
  "Fatsia polycarpa",
  "Felicia amelloides",
  "Festuca",
  "Ficinia truncata",
  "Ficoïde",
  "Ficus benghalensis",
  "Ficus benjamina",
  "Ficus carica",
  "Ficus microcarpa",
  "Ficus pumila",
  "Ficus repens",
  "Ficus retusa",
  "Filipendula rubra",
  "Fittonia",
  "Fockea edulis",
  "Foeniculum vulgare",
  "Foeniculum vulgare 'purpureum'",
  "Forsythia",
  "Fothergilla",
  "Fragaria",
  "Franklinia alatamaha",
  "Fraxinus excelsior",
  "Freesia",
  "Fuchsia",
  "Gaillardia",
  "Galanthus",
  "Galega officinalis",
  "Galium odoratum",
  "Galtonia candicans",
  "Gardenia",
  "Garrya elliptica",
  "Gaultheria",
  "Gaura",
  "Gelsemium sempervirens",
  "Geranium",
  "Geum",
  "Gillenia",
  "Ginkgo biloba",
  "Gladiolus",
  "Gladiolus callianthus",
  "Gloriosa superba var. rothschildiana",
  "Gomphrena globosa",
  "Gordlinia grandiflora",
  "Gossypium",
  "Graptopetalum",
  "Grevillea juniperina",
  "Griselinia littoralis",
  "Gunnera manicata",
  "Gynostemma pentaphyllum",
  "Habenaria radiata",
  "Haemanthus multiflorus",
  "Hakonechloa macra",
  "Halesia carolina",
  "Hardenbergia violacea",
  "Haworthia",
  "Hebe",
  "Hedera",
  "Hedychium",
  "Hedychium coronarium",
  "Helenium",
  "Helianthus annuus",
  "Helichrysum",
  "Heliconia",
  "Helictotrichon sempervirens",
  "Heliopsis",
  "Helleborus",
  "Hemerocallis",
  "Heptacodium miconioides",
  "Heptaleurum brassaia",
  "Hermodactylus tuberosa",
  "Hesperis matronalis",
  "Heuchera",
  "Hibanobambusa tranquillans",
  "Hibiscus esculentus",
  "Hibiscus moscheutos",
  "Hibiscus syriacus",
  "Hieracium aurantiacum",
  "Hippeastrum",
  "Hosta",
  "Houstonia caerulea",
  "Houttuynia cordata",
  "Hovenia dulcis",
  "Howea",
  "Hoya",
  "Hyacinthus",
  "Hydrangea",
  "Hymenocallis x festalis",
  "Ilex",
  "Ilex crenata",
  "Illicium floridanum",
  "Impatiens",
  "Indigofera heterantha",
  "Ipheion uniflorum",
  "Ipomea batatas",
  "Ipomoea",
  "Ipomoea batatas",
  "Iresine herbstii",
  "Iris",
  "Iris barbata",
  "Iris tuberosa",
  "Iris unguicularis",
  "Ismene x festalis",
  "Isodon longituba",
  "Isolepis cernua",
  "Itea ilicifolia",
  "Itea virginica",
  "Jasminum nudiflorum",
  "Jasminum officinale",
  "Jasminum sambac",
  "Juglans regia",
  "Juniperus",
  "Kalanchoe",
  "Kalimeris incisa",
  "Keiskea japonica",
  "Kerria japonica",
  "Kniphofia",
  "Koeleria glauca",
  "Koelreuteria paniculata",
  "Laburnum",
  "Lactuca",
  "Laelia",
  "Lagerstroemia",
  "Lamium",
  "Lantana",
  "Larix",
  "Laurier jaune",
  "Laurus nobilis",
  "Lavandula",
  "Lavatera",
  "Lavatera trimestris",
  "Leonotis leonurus",
  "Leontopodium alpinum",
  "Lepidium sativum",
  "Leptinella",
  "Lespedeza thunbergii",
  "Leucadendron",
  "Leucanthemum",
  "Leucanthemum x superbum",
  "Leucojum",
  "Leucophyllum frutescens",
  "Leucophyta brownii",
  "Leucothoe",
  "Lewisia",
  "Liatris",
  "Licuala grandis",
  "Ligularia",
  "Ligustrum",
  "Lilium",
  "Lilium martagon",
  "Lilium pardalinum",
  "Limnanthes douglasii",
  "Linum grandiflorum",
  "Lippia citrodora",
  "Lippia dulcis",
  "Lippia nodiflora",
  "Liriodendron tulipifera",
  "Liriope muscari",
  "Lithodora diffusa",
  "Lithops",
  "Lobelia",
  "Lomatia tinctoria",
  "Lonicera",
  "Lonicera caerulea",
  "Lonicera henryi",
  "Lophomyrtus x ralphii",
  "Lophospermum",
  "Ludisia discolor",
  "Luma apiculata",
  "Luma chequen",
  "Lunaria",
  "Lupinus",
  "Luzula",
  "Lychnis coronaria",
  "Lycianthes rantonnetii",
  "Lycoris radiata",
  "Lysimachia",
  "Lythrum salicaria",
  "Macleaya cordata",
  "Macleaya pomifera",
  "Magnolia",
  "Magnolia grandiflora",
  "Magnolia stellata",
  "Mahonia",
  "Malcolmia maritima",
  "Malus",
  "Malva",
  "Marrubium vulgare",
  "Matthiola incana",
  "Meconopsis betonicifolia",
  "Medicago arborea",
  "Melianthus major",
  "Melilotus",
  "Melissa",
  "Melothria scabra",
  "Mentha",
  "Mesembryanthemum crystallinum",
  "Metrosideros excelsa",
  "Michelia",
  "Millettia japonica",
  "Mimosa pudica",
  "Mimulus",
  "Mirabilis",
  "Miscanthus",
  "Miscanthus nepalensis",
  "Moltkia",
  "Momordica charantia",
  "Monarda",
  "Montia perfoliata",
  "Morina longifolia",
  "Moringa oleifera",
  "Morus",
  "Muehlenbeckia",
  "Muhlenbergia capillaris",
  "Murraya paniculata",
  "Musa",
  "Muscari",
  "Myosotis",
  "Myriophyllum aquaticum",
  "Myrsine africana",
  "Myrtus apiculata",
  "Myrtus chequen",
  "Myrtus luma",
  "Narcissus",
  "Nasturtium officinale",
  "Nectaroscordium siculum",
  "Nelumbo",
  "Nerine bowdenii",
  "Nerium oleander",
  "Nicandra physaloides",
  "Nicotiana",
  "Nigella damascena",
  "Nuphar",
  "Nuphar lutea",
  "Nymphea",
  "Nyssa sylvatica",
  "Ocimum",
  "Ocimum kilimandscharicum",
  "Oenothera",
  "Olea europea",
  "Oncidium",
  "Onychium japonicum",
  "Opuntia ficus-indica",
  "Orbea variegata",
  "Origanum majorana",
  "Origanum vulgare",
  "Osmoxylon lineare",
  "Osmunda regalis",
  "Oxalis articulata",
  "Oxalis deppei",
  "Oxalis tetraphylla",
  "Oxydendron arboreum",
  "Oxypetalum caeruleum",
  "Pachyphragma macrophyllum",
  "Pachysandra terminalis",
  "Paeonia",
  "Pandorea jasminoides",
  "Panicum virgatum",
  "Papaver croceum",
  "Papaver nudicaule",
  "Papaver orientale",
  "Papaver rhoeas",
  "Paris polyphylla",
  "Parrotia persica",
  "Parthenocissus",
  "Passiflora",
  "Patrinia",
  "Pavonia multiflora",
  "Pecteilis radiata",
  "Pelargonium",
  "Pennisetum glaucum",
  "Penstemon",
  "Pentas lanceolata",
  "Peperomia",
  "Pernettya",
  "Persicaria amplexicaulis",
  "Petasites",
  "Petroselinum",
  "Petunia",
  "Phacelia tanacetifolia",
  "Phalaenopsis",
  "Phalaris arundinacea",
  "Phaseolus",
  "Phaseolus coccineus",
  "Philotheca myoporoides",
  "Phlox",
  "Phoenix canariensis",
  "Phoenix roebelenii",
  "Photinia",
  "Phragmipedium",
  "Phuopsis stylosa",
  "Phygelius capensis",
  "Phyllostachys",
  "Physalis alkekengi",
  "Physalis peruviana",
  "Physostegia virginiana",
  "Picea",
  "Pilea peperomioides",
  "Pileostegia viburnoides",
  "Pilosella aurantiaca",
  "Pimelea ferruginea",
  "Pinus",
  "Pistachier",
  "Pistacia lentiscus",
  "Pittosporum tenuifolium",
  "Pittosporum tobira",
  "Platanus",
  "Platycerium",
  "Platycodon grandiflora",
  "Plectranthus australis",
  "Pleione",
  "Plumbago auriculata",
  "Polianthes tuberosa",
  "Polygonatum",
  "Polygonum baldschuanicum",
  "Polyscias",
  "Populus",
  "Populus tremula",
  "Potentilla",
  "Primula",
  "Primula juliae",
  "Primula veris",
  "Prostanthera cuneata",
  "Protea",
  "Prunus avium",
  "Prunus cerasus",
  "Prunus domestica",
  "Prunus domestica n-subsp. italica",
  "Prunus laurocerasus",
  "Prunus lusitanica",
  "Prunus mume",
  "Prunus padus",
  "Prunus persica",
  "Prunus spinosa",
  "Prunus tomentosa",
  "Prunus triloba",
  "Pteris",
  "Pterostyrax",
  "Pulmonaria",
  "Pulsatilla vulgaris",
  "Puschkinia 'libanotica'",
  "Pyrethrum roseum",
  "Pyrus",
  "Pyrus communis",
  "Quercus",
  "Quercus ilex",
  "Quercus suber",
  "Rabdosia longituba",
  "Ranunculus",
  "Raoulia",
  "Raphanus sativus",
  "Raphanus sativus niger",
  "Raphanus sativus var. longipinnatus",
  "Reinwardtia indica",
  "Reseda",
  "Rhaphiolepis",
  "Rheum rhaponticum",
  "Rhipsalis",
  "Rhodochiton atrosanguineus",
  "Rhododendron",
  "Rhododendron obtusum",
  "Rhus typhina",
  "Rhynchospora colorata",
  "Ribes",
  "Ribes nigrum",
  "Robinia pseudoacacia",
  "Rodgersia",
  "Romneya coulteri",
  "Rosa",
  "Rosa canina",
  "Rosa chinensis viridiflora",
  "Rosa x hybrida astronomia",
  "Rosmarinus officinalis",
  "Rostrinucula dependens",
  "Rubus",
  "Rubus fruticosus",
  "Rubus idaeus",
  "Rubus thibetanus",
  "Rudbeckia",
  "Rumex acetosa",
  "Rumex patientia",
  "Sagina subulata",
  "Saintpaulia",
  "Salix",
  "Salix integra 'hakuro nishiki'",
  "Salvia",
  "Salvia officinalis",
  "Sambucus",
  "Sambucus nigra",
  "Sanguinaria canadensis",
  "Sanguisorba",
  "Saponaria officinalis",
  "Sarracenia",
  "Sassafras albidum",
  "Satureja",
  "Satureja douglasii",
  "Saxifraga",
  "Scadoxus multiflorus",
  "Schisandra grandiflora",
  "Schizachyrium scoparium",
  "Schizophragma hydrangeoides",
  "Schizostylis coccinea",
  "Schlumbergera",
  "Sciadopitys verticillata",
  "Scilla peruviana",
  "Scleranthus uniflorus",
  "Sechium",
  "Sedum",
  "Sedum morganianum",
  "Semiarundinaria",
  "Sempervivum",
  "Senecio cineraria",
  "Senecio monroi",
  "Senna corymbosa",
  "Sequoia",
  "Silene",
  "Sinapis alba",
  "Sinojackia xylocarpa",
  "Sisyrinchium",
  "Sisyrinchium angustifolium",
  "Solanum aethiopicum",
  "Solanum crispum",
  "Solanum jasminoïdes",
  "Solanum muricatum",
  "Solanum rantonnetii",
  "Soleirolia",
  "Solenostemon",
  "Solidago",
  "Sollya heterophylla",
  "Sophora japonica",
  "Sophora microphylla",
  "Sorbaria sorbifolia",
  "Sorbus aucuparia",
  "Sorbus domestica",
  "Sorbus torminalis",
  "Sparaxis",
  "Spartium junceum",
  "Spilanthes oleraceae",
  "Spiraea",
  "Spiraea x vanhouttei",
  "Stachys affinis",
  "Stachys byzantina",
  "Stachys lanata",
  "Stachyurus chinensis",
  "Stapelia variegata",
  "Staphylea pinnata",
  "Statice latifolium",
  "Statice sinuata",
  "Stauntonia",
  "Stephanandra incisa 'crispa'",
  "Sternbergia",
  "Stewartia pseudocamellia",
  "Stipa tenuissima",
  "Stratiotes aloides",
  "Strelitzia reginae",
  "Streptocarpus",
  "Strobilanthes",
  "Styrax",
  "Syngonium podophyllum",
  "Syringa",
  "Tagetes patula",
  "Tamarix",
  "Tanacetum balsamita",
  "Tanacetum coccineum",
  "Tasmannia lanceolata",
  "Taxus",
  "Telopea",
  "Tetradenia riparia",
  "Tetradium daniellii var. hupehensis",
  "Teucrium fruticans",
  "Thalictrum",
  "Thamnochortus cinereus",
  "Thevetia peruviana",
  "Thuya",
  "Thymus",
  "Thymus x citriodorus",
  "Tiarella",
  "Tigridia",
  "Tilia",
  "Tillia",
  "Titanotrichum oldhamii",
  "Tolmiea",
  "Toona sinensis",
  "Torenia",
  "Trachelium",
  "Trachelospermum jasminoides",
  "Trachycarpus",
  "Trachystemon orientalis",
  "Tricyrtis",
  "Trillium",
  "Triteleia",
  "Trochodendron aralioides",
  "Tropaeolum",
  "Tulbaghia violacea",
  "Tulipa",
  "Tweedia caerulea",
  "Typha",
  "Ulex europaeus",
  "Ulmus",
  "Uncinia rubra",
  "Urginea maritima",
  "Vaccinium",
  "Vaccinium macrocarpon",
  "Valerianella",
  "Veltheimia",
  "Verbascum",
  "Verbena bonariensis",
  "Verbena officinalis",
  "Verbena rigida",
  "Verbena x hybrida",
  "Viburnum",
  "Viburnum",
  "Viburnum lantana",
  "Viburnum opulus",
  "Viburnum plicatum",
  "Viburnum rhytidophyllum",
  "Viburnum tinus",
  "Viburnum x burkwoodii",
  "Vigna unguiculata",
  "Vinca",
  "Viola",
  "Viola cornuta",
  "Viola odorata",
  "Vitex agnus-castus",
  "Vitis coignetiae",
  "Vitis vinifera",
  "Waldsteinia ternata",
  "Wasabia japonica",
  "Washingtonia filifera",
  "Weigela",
  "Westringia longifolia",
  "Wisteria",
  "Wisteria floribunda",
  "Yucca",
  "Yucca elephantipes",
  "Zamioculcas",
  "Zantedeschia",
  "Zanthoxylum",
  "Zingiber mioga",
  "Zinnia",
  "Ziziphus jujuba",
  "Zoysia tenuifolia",
];
